"""Core logic of TAPA."""

__copyright__ = """
Copyright (c) 2025 RapidStream Design Automation, Inc. and contributors.
All rights reserved. The contributor(s) of this file has/have agreed to the
RapidStream Contributor License Agreement.
"""

import decimal
import functools
import logging
import os
import shutil
import tempfile
from graphlib import TopologicalSorter
from pathlib import Path
from types import TracebackType
from typing import Self
from xml.etree import ElementTree as ET

from tapa.common.paths import get_tapacc_cflags
from tapa.common.target import Target
from tapa.instance import Instance
from tapa.program.directory import ProgramDirectoryMixin
from tapa.program.hls import ProgramHlsMixin
from tapa.program.pack import ProgramPackMixin
from tapa.program.synthesis import ProgramSynthesisMixin
from tapa.task import Task
from tapa.verilog.util import Pipeline
from tapa.verilog.xilinx.const import DONE, START

_logger = logging.getLogger().getChild(__name__)


class Program(  # TODO: refactor this class
    ProgramDirectoryMixin,
    ProgramHlsMixin,
    ProgramPackMixin,
    ProgramSynthesisMixin,
):
    """Describes a TAPA program.

    Attributes:
      top: Name of the top-level module.
      work_dir: Working directory.
      is_temp: Whether to delete the working directory after done.
      _tasks: Dict mapping names of tasks to Task objects.
      files: Dict mapping file names to contents that appear in the HDL directory.
      target: The target flow of the program, e.g., "xilinx-hls" or "xilinx-vitis".
    """

    # ruff: noqa: PLR0913,PLR0917
    def __init__(
        self,
        obj: dict,
        target: str | Target,
        work_dir: str | None = None,
        gen_templates: tuple[str, ...] = (),
        floorplan_slots: list[str] | None = None,
        flattened: bool = False,
        slot_task_name_to_fp_region: dict[str, str] | None = None,
    ) -> None:
        """Construct Program object from a json file.

        Args:
          obj: json object.
          target: Target flow of the program, e.g., "xilinx-hls" or "xilinx-vitis".
          work_dir: Specify a working directory as a string. If None, a temporary
              one will be created.
          gen_templates: Tuple of task names that are templates. If a task is
              specified as a template, its verilog module will only contains io
              ports and no logic.
          floorplan_slots: Tasks that are generated by floorplanning.
          flattened: Whether the TAPA graph has been flattened.
          slot_task_name_to_fp_region: Mapping from slot task names to
              floorplan region names.
        """
        if floorplan_slots is None:
            floorplan_slots = []
        self.top: str = obj["top"]
        self.cflags = " ".join((*(obj.get("cflags", [])), *get_tapacc_cflags()))
        self.target = Target(target)
        if work_dir is None:
            self.work_dir = tempfile.mkdtemp(prefix="tapa-")
            self.is_temp = True
        else:
            self.work_dir = os.path.abspath(work_dir)
            os.makedirs(self.work_dir, exist_ok=True)
            self.is_temp = False
        self._tasks: dict[str, Task] = {}

        task_names = list(
            TopologicalSorter(
                {k: set(v.get("tasks", ())) for k, v in obj["tasks"].items()}
            ).static_order()
        )
        for template in gen_templates:
            assert template in task_names, (
                f"template task {template} not found in design"
            )
        self.gen_templates = gen_templates
        self.flattened = flattened

        for name in task_names:
            task_properties = obj["tasks"][name]
            task = Task(
                name=name,
                code=task_properties["code"],
                level=task_properties["level"],
                tasks=task_properties.get("tasks", {}),
                fifos=task_properties.get("fifos", {}),
                ports=task_properties.get("ports", []),
                target_type=task_properties["target"],
                is_slot=(name in floorplan_slots),
            )
            if not task.is_upper or task.tasks:
                self._tasks[name] = task

            # add ignored tasks to gen_templates
            if task_properties["target"] == "ignore" and name not in self.gen_templates:
                self.gen_templates += (name,)

        self.files: dict[str, str] = {}
        self.slot_task_name_to_fp_region = slot_task_name_to_fp_region

    def close(self) -> None:
        """Clean up temporary working directory if one was created."""
        if self.is_temp and os.path.exists(self.work_dir):
            shutil.rmtree(self.work_dir)
            self.is_temp = False  # prevent double-cleanup

    def __enter__(self) -> Self:
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None:
        self.close()

    @property
    def top_task(self) -> Task:
        return self._tasks[self.top]

    @property
    def start_q(self) -> Pipeline:
        return Pipeline(START.name)

    @property
    def done_q(self) -> Pipeline:
        return Pipeline(DONE.name)

    @staticmethod
    def _get_custom_rtl_files(rtl_paths: tuple[Path, ...]) -> list[Path]:
        custom_rtl: list[Path] = []
        for path in rtl_paths:
            if path.is_file():
                custom_rtl.append(path)
            elif path.is_dir():
                rtl_files = list(path.rglob("*"))
                if not rtl_files:
                    msg = f"no rtl files found in {path}"
                    raise ValueError(msg)
                custom_rtl.extend(rtl_files)
            elif path.exists():
                msg = f"unsupported path: {path}"
                raise ValueError(msg)
            else:
                msg = f"path does not exist: {path.absolute()}"
                raise ValueError(msg)
        return custom_rtl

    def get_task(self, name: str) -> Task:
        return self._tasks[name]

    @functools.cache
    def _get_hls_report_xml(self, name: str) -> ET.ElementTree:
        tree = ET.ElementTree()
        tree.parse(os.path.join(self.report_dir, f"{name}_csynth.xml"))
        return tree

    def _get_part_num(self, name: str) -> str:
        xml = self._get_hls_report_xml(name)
        part = xml.find("./UserAssignments/Part")
        assert part is not None
        assert part.text is not None
        return part.text

    def get_area(self, name: str) -> dict[str, int]:
        node = self._get_hls_report_xml(name).find("./AreaEstimates/Resources")
        assert node is not None
        return {x.tag: int(x.text or "-1") for x in sorted(node, key=lambda x: x.tag)}

    def get_clock_period(self, name: str) -> decimal.Decimal:
        xml = self._get_hls_report_xml(name)
        period = xml.find(
            "./PerformanceEstimates/SummaryOfTimingAnalysis/EstimatedClockPeriod",
        )
        assert period is not None
        assert period.text is not None
        return decimal.Decimal(period.text)

    @staticmethod
    def get_inst_by_port_arg_name(
        target_task: str | None, parent_task: Task, port_arg_name: str
    ) -> Instance:
        matched_inst = next(
            (
                inst
                for inst in parent_task.instances
                if (not target_task or inst.task.name == target_task)
                and any(arg.name == port_arg_name for arg in inst.args)
            ),
            None,
        )
        assert matched_inst is not None
        return matched_inst
