[package]
name = "tapa-codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-embed = { workspace = true }
serde_json.workspace = true
thiserror.workspace = true
tapa-ir.workspace = true
tapa-protocol.workspace = true
tapa-rtl.workspace = true

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
