# Copyright (c) 2024 RapidStream Design Automation, Inc. and contributors.
# All rights reserved. The contributor(s) of this file has/have agreed to the
# RapidStream Contributor License Agreement.

name: "Run docker as the build environment"
description: "Run commands in the given docker image with the build environment setup"

inputs:
  image:
    description: "Docker image to use"
    required: false
    default: "tapa/buildenv:local"
  run:
    description: "Command to run in the docker container"
    required: true
  dockerOptions:
    description: "Additional options to pass to the docker run command"
    required: false
  shmSize:
    description: "Shared memory size for the docker container"
    required: false
    default: "4g"
  memory:
    description: "Memory limit for the docker container"
    required: false
    default: "96g"
  cpus:
    description: "CPU limit for the docker container"
    required: false
    default: "16"
  pidsLimit:
    description: "PID limit for the docker container"
    required: false
    default: "8192"

runs:
  using: "composite"
  steps:
    - name: Ensure the build cache directories are present and owned by the current user
      run: |
        mkdir -p ~/.cache/tapa-cache
        mkdir -p ~/.cache/tapa-local
      shell: bash

    - name: Run commands in the Docker container with the build environment setup
      run: |
        label=tapa-github-runner
        containers=($(docker ps --filter=label="${label}" --format={{.ID}}))
        if (( ${#containers[@]} )); then
          docker stop "${containers[@]}"
        fi

        # Make a copy of bazelrc which is readable by the runner.
        local_bazelrc=~/.cache/tapa-local/bazelrc
        cp /etc/bazel.bazelrc "${local_bazelrc}" || touch "${local_bazelrc}"

        docker run \
          --rm \
          --init \
          --shm-size=${{ inputs.shmSize }} \
          --memory=${{ inputs.memory }} \
          --cpus=${{ inputs.cpus }} \
          --pids-limit=${{ inputs.pidsLimit }} \
          --label="${label}" \
          --mac-address=${{ env.MAC_ADDRESS }} \
          -v "${local_bazelrc}":/etc/bazel.bazelrc:ro \
          -v ${TAPA_LICENSE_DIR:-/share/software/licenses}:/opt/licenses:ro \
          -v ${TAPA_TOOLS_DIR:-/share/software/tools}:/opt/tools:ro \
          -v ${TAPA_PLATFORMS_DIR:-/share/software/xilinx/platforms}:/opt/xilinx/platforms:ro \
          -v ${{ github.workspace }}:/workspace \
          -v ~/.cache/tapa-cache:/tmp/home/.cache \
          -v ~/.cache/tapa-local:/tmp/home/.local \
          -v ${GITHUB_STEP_SUMMARY}:/workspace/.github_step_summary \
          -w /workspace \
          -e GITHUB_ACTIONS=true \
          -e GITHUB_STEP_SUMMARY=/workspace/.github_step_summary \
          -e LM_LICENSE_FILE=/opt/licenses/xilinx-ci.lic \
          -e VIVADO_IMPL_JOBS=1 \
          -e VIVADO_SYNTH_JOBS=1 \
          -e VIVADO_MAX_THREADS=1 \
          -e USER="$(id -u)" \
          -u $(id -u):$(id -g) \
          ${{ inputs.dockerOptions }} \
          --entrypoint=/bin/bash \
          ${{ inputs.image }} \
          -c " \
            set -xe
            ${{ inputs.run }}
          "
      shell: bash
