/* Single declaration point for the FRT C ABIs implemented in Rust.
 * GENERATED by cbindgen from fpga-runtime/frt — do not edit by hand.
 *   * `frt_instance_*`     -> fpga-runtime/frt/src/ffi.rs
 *   * `frt_shmq_*`         -> fpga-runtime/frt/src/shm_ffi.rs
 */

#pragma once

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

extern "C" {

/// Return the error message recorded by the most recent failed `frt_*`
/// call on this thread, or null if the last call succeeded (or none ran).
///
/// The returned pointer borrows from a per-thread slot; it is valid until
/// the next `frt_*` call on this thread (or thread exit, whichever
/// comes first). Each thread has an independent error slot. Copy the
/// string if it must outlive that point.
const char *frt_last_error_message();

void *frt_instance_open(const char *path, const char *simulator);

void frt_instance_close(void *handle);

int frt_instance_set_scalar_bytes(void *handle,
                                  uint32_t index,
                                  const uint8_t *value,
                                  uintptr_t size);

int frt_instance_set_buffer_arg_typed(void *handle,
                                      uint32_t index,
                                      uint8_t *ptr,
                                      uintptr_t bytes,
                                      int tag);

int frt_instance_set_stream_arg(void *handle, uint32_t index, const char *shm_path);

int frt_instance_write_to_device(void *handle);

int frt_instance_read_from_device(void *handle);

int frt_instance_exec(void *handle);

int frt_instance_finish(void *handle);

int frt_instance_kill(void *handle);

int frt_instance_is_finished(void *handle);

uint64_t frt_instance_load_ns(void *handle);

uint64_t frt_instance_compute_ns(void *handle);

uint64_t frt_instance_store_ns(void *handle);

void *frt_shmq_create(uint32_t depth, uint32_t width, char *out_path, uintptr_t out_path_len);

void frt_shmq_destroy(void *handle);

int frt_shmq_empty(const void *handle);

int frt_shmq_full(const void *handle);

int frt_shmq_push(void *handle, const uint8_t *data, uintptr_t len);

int frt_shmq_front(const void *handle, uint8_t *out, uintptr_t len);

int frt_shmq_pop(void *handle, uint8_t *out, uintptr_t len);

}  // extern "C"
