version: 2

build:
  os: ubuntu-24.04
  tools:
    rust: latest
  commands:
    - cargo install mdbook@0.4.52 mdbook-admonish@1.20.0
    - cd docs && mdbook-admonish install .
    - mdbook build docs/ --dest-dir "$READTHEDOCS_OUTPUT/html"
