[book]
title = "TAPA Documentation"
authors = ["TAPA community maintainers and contributors"]
language = "en"
src = "src"

[output.html]
site-url = "/tapa/"
git-repository-url = "https://github.com/tuna/tapa"
edit-url-template = "https://github.com/tuna/tapa/edit/main/docs/src/{path}"
