[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log

[program:dockerd]
command=/usr/local/bin/dockerd --userland-proxy=false --group=docker
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/dockerd-stdout.log
stderr_logfile=/var/log/supervisor/dockerd-stderr.log
priority=10

[program:runner]
command=/home/runner/actions-runner/run.sh
user=runner
environment=HOME="/home/runner",USER="runner"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/runner-stdout.log
stderr_logfile=/var/log/supervisor/runner-stderr.log
priority=20
startsecs=10
startretries=10
