pub mod names;
pub mod verilator;
pub mod xsim;

use std::collections::HashMap;

use crate::metadata::{normalized_scalar_bytes, KernelSpec};

#[derive(Clone)]
pub struct ScalarWord {
    pub reg_offset: u32,
    pub value_u32: u32,
}

/// Look up the register offset for an arg name in the scalar register map.
/// Falls back to `"{name}_offset"` if the exact name is not found.
pub fn lookup_register_offset(spec: &KernelSpec, name: &str) -> u32 {
    spec.scalar_register_map
        .get(name)
        .or_else(|| {
            let key = format!("{name}_offset");
            spec.scalar_register_map.get(&key)
        })
        .copied()
        .unwrap_or(0)
}

/// Read all Verilog file contents for peek-port detection and similar scans.
pub fn read_verilog_contents(spec: &KernelSpec) -> Vec<String> {
    spec.verilog_files
        .iter()
        .filter_map(|f| std::fs::read_to_string(f).ok())
        .collect()
}

/// Direct-offset scalar port on the DUT module.
///
/// Vitis HLS through 2024.2 emits `<name>_offset` for `offset=direct`
/// `m_axi` arguments; 2025.1+ renamed the generated scalar to
/// `<name>_r`. Prefer the conventional spelling and fall back to the
/// 2025 one only when the RTL declares it exclusively, so the
/// testbench pins whatever port the packaged module actually has.
pub fn direct_offset_port_name(verilog_contents: &[String], name: &str) -> String {
    let conventional = format!("{name}_offset");
    if port_declared(verilog_contents, &conventional) {
        return conventional;
    }
    let vitis_2025 = format!("{name}_r");
    if port_declared(verilog_contents, &vitis_2025) {
        return vitis_2025;
    }
    conventional
}

/// Whether any Verilog file declares a port with this exact name.
fn port_declared(verilog_contents: &[String], port: &str) -> bool {
    let pattern = format!(
        r"(?m)\b(?:input|output|inout)\b[^;\n]*\b{}\b",
        regex_lite::escape(port)
    );
    let re = regex_lite::Regex::new(&pattern).unwrap();
    verilog_contents.iter().any(|text| re.is_match(text))
}

/// Classify spec args into four groups by applying backend-specific constructors.
#[allow(
    clippy::implicit_hasher,
    reason = "generic hasher adds no value for internal helper"
)]
pub fn classify_args<M, S, T>(
    spec: &KernelSpec,
    scalar_values: &HashMap<u32, Vec<u8>>,
    verilog_contents: &[String],
    make_mmap: impl Fn(&crate::metadata::ArgSpec, u32) -> M,
    make_scalar: impl Fn(&crate::metadata::ArgSpec, u32, u32, &[u8]) -> S,
    make_stream: impl Fn(&crate::metadata::ArgSpec, usize, Option<String>, bool) -> T,
) -> (Vec<M>, Vec<S>, Vec<T>, Vec<T>) {
    use crate::metadata::{ArgKind, Mode, StreamDir, StreamProtocol};
    use names::{infer_peek_name, stream_peek_ports_exist};

    let mut mmaps = vec![];
    let mut scalars = vec![];
    let mut streams_in = vec![];
    let mut streams_out = vec![];

    for arg in &spec.args {
        match &arg.kind {
            ArgKind::Mmap { .. } => {
                let offset = lookup_register_offset(spec, &arg.name);
                mmaps.push(make_mmap(arg, offset));
            }
            ArgKind::Scalar { width } => {
                let offset = lookup_register_offset(spec, &arg.name);
                let bytes =
                    normalized_scalar_bytes(*width, scalar_values.get(&arg.id).map(Vec::as_slice));
                scalars.push(make_scalar(arg, *width, offset, &bytes));
            }
            ArgKind::Stream {
                width,
                dir,
                protocol,
                ..
            } => {
                let w = (*width as usize).div_ceil(8);
                let axis = *protocol == StreamProtocol::Axis;
                let peek = if spec.mode == Mode::Hls && *dir == StreamDir::In {
                    infer_peek_name(&arg.name).filter(|cand| {
                        stream_peek_ports_exist(verilog_contents, &spec.top_name, cand)
                    })
                } else {
                    None
                };
                let s = make_stream(arg, w, peek, axis);
                match dir {
                    StreamDir::In => streams_in.push(s),
                    StreamDir::Out => streams_out.push(s),
                }
            }
        }
    }
    (mmaps, scalars, streams_in, streams_out)
}

/// AXI4 signal names for a single mmap port.
///
/// Generated by a backend-specific naming function (e.g.
/// `escaped_verilog_signal` for xsim, `cpp_signal` for Verilator).
#[derive(Clone)]
pub struct AxiSignals {
    pub araddr: String,
    pub arburst: String,
    pub arcache: String,
    pub arid: String,
    pub arlen: String,
    pub arlock: String,
    pub arprot: String,
    pub arqos: String,
    pub arready: String,
    pub arsize: String,
    pub arvalid: String,
    pub awaddr: String,
    pub awburst: String,
    pub awcache: String,
    pub awid: String,
    pub awlen: String,
    pub awlock: String,
    pub awprot: String,
    pub awqos: String,
    pub awready: String,
    pub awsize: String,
    pub awvalid: String,
    pub bid: String,
    pub bready: String,
    pub bresp: String,
    pub bvalid: String,
    pub rdata: String,
    pub rid: String,
    pub rlast: String,
    pub rready: String,
    pub rresp: String,
    pub rvalid: String,
    pub wdata: String,
    pub wlast: String,
    pub wready: String,
    pub wstrb: String,
    pub wvalid: String,
}

impl AxiSignals {
    pub fn new(name: &str, sig: impl Fn(&str, &str, &str) -> String) -> Self {
        Self {
            araddr: sig("m_axi_", name, "_ARADDR"),
            arburst: sig("m_axi_", name, "_ARBURST"),
            arcache: sig("m_axi_", name, "_ARCACHE"),
            arid: sig("m_axi_", name, "_ARID"),
            arlen: sig("m_axi_", name, "_ARLEN"),
            arlock: sig("m_axi_", name, "_ARLOCK"),
            arprot: sig("m_axi_", name, "_ARPROT"),
            arqos: sig("m_axi_", name, "_ARQOS"),
            arready: sig("m_axi_", name, "_ARREADY"),
            arsize: sig("m_axi_", name, "_ARSIZE"),
            arvalid: sig("m_axi_", name, "_ARVALID"),
            awaddr: sig("m_axi_", name, "_AWADDR"),
            awburst: sig("m_axi_", name, "_AWBURST"),
            awcache: sig("m_axi_", name, "_AWCACHE"),
            awid: sig("m_axi_", name, "_AWID"),
            awlen: sig("m_axi_", name, "_AWLEN"),
            awlock: sig("m_axi_", name, "_AWLOCK"),
            awprot: sig("m_axi_", name, "_AWPROT"),
            awqos: sig("m_axi_", name, "_AWQOS"),
            awready: sig("m_axi_", name, "_AWREADY"),
            awsize: sig("m_axi_", name, "_AWSIZE"),
            awvalid: sig("m_axi_", name, "_AWVALID"),
            bid: sig("m_axi_", name, "_BID"),
            bready: sig("m_axi_", name, "_BREADY"),
            bresp: sig("m_axi_", name, "_BRESP"),
            bvalid: sig("m_axi_", name, "_BVALID"),
            rdata: sig("m_axi_", name, "_RDATA"),
            rid: sig("m_axi_", name, "_RID"),
            rlast: sig("m_axi_", name, "_RLAST"),
            rready: sig("m_axi_", name, "_RREADY"),
            rresp: sig("m_axi_", name, "_RRESP"),
            rvalid: sig("m_axi_", name, "_RVALID"),
            wdata: sig("m_axi_", name, "_WDATA"),
            wlast: sig("m_axi_", name, "_WLAST"),
            wready: sig("m_axi_", name, "_WREADY"),
            wstrb: sig("m_axi_", name, "_WSTRB"),
            wvalid: sig("m_axi_", name, "_WVALID"),
        }
    }
}

/// Stream signal names for a single stream port.
#[derive(Clone)]
pub struct StreamSignals {
    pub empty_n: String,
    pub dout: String,
    pub din: String,
    pub read: String,
    pub full_n: String,
    pub write: String,
    pub tdata: String,
    pub tvalid: String,
    pub tready: String,
    pub tlast: String,
    pub peek_empty_n: String,
    pub peek_dout: String,
}

impl StreamSignals {
    pub fn new(name: &str, peek_name: &str, sig: impl Fn(&str, &str, &str) -> String) -> Self {
        Self {
            empty_n: sig("", name, "_empty_n"),
            dout: sig("", name, "_dout"),
            din: sig("", name, "_din"),
            read: sig("", name, "_read"),
            full_n: sig("", name, "_full_n"),
            write: sig("", name, "_write"),
            tdata: sig("", name, "_TDATA"),
            tvalid: sig("", name, "_TVALID"),
            tready: sig("", name, "_TREADY"),
            tlast: sig("", name, "_TLAST"),
            peek_empty_n: sig("", peek_name, "_empty_n"),
            peek_dout: sig("", peek_name, "_dout"),
        }
    }
}

pub fn scalar_words(base_offset: u32, bytes: &[u8]) -> Vec<ScalarWord> {
    let mut words = Vec::new();
    for (i, chunk) in bytes.chunks(4).enumerate() {
        let mut raw = [0u8; 4];
        raw[..chunk.len()].copy_from_slice(chunk);
        words.push(ScalarWord {
            reg_offset: base_offset + (i as u32) * 4,
            value_u32: u32::from_le_bytes(raw),
        });
    }
    if words.is_empty() {
        words.push(ScalarWord {
            reg_offset: base_offset,
            value_u32: 0,
        });
    }
    words
}

#[cfg(test)]
mod tests {
    use super::direct_offset_port_name;

    #[test]
    fn direct_offset_prefers_conventional_spelling() {
        let rtl = vec!["module m(mmap_offset);\ninput [63:0] mmap_offset;\nendmodule".to_owned()];
        assert_eq!(direct_offset_port_name(&rtl, "mmap"), "mmap_offset");
    }

    #[test]
    fn direct_offset_falls_back_to_vitis_2025_spelling() {
        let rtl = vec!["module m(mmap_r);\ninput [63:0] mmap_r;\nendmodule".to_owned()];
        assert_eq!(direct_offset_port_name(&rtl, "mmap"), "mmap_r");
    }

    #[test]
    fn direct_offset_defaults_to_conventional_when_neither_declared() {
        let rtl = vec!["module m(ap_clk);\ninput ap_clk;\nendmodule".to_owned()];
        assert_eq!(direct_offset_port_name(&rtl, "mmap"), "mmap_offset");
    }

    #[test]
    fn direct_offset_ignores_non_declaration_mentions() {
        // `mmap_offset` appearing only in a comment must not mask the
        // actually-declared 2025-style port.
        let rtl = vec![
            "// carries mmap_offset semantics\nmodule m(mmap_r);\ninput [63:0] mmap_r;\nendmodule"
                .to_owned(),
        ];
        assert_eq!(direct_offset_port_name(&rtl, "mmap"), "mmap_r");
    }

    /// The probe order is shared with `tapa-codegen`'s child-instance
    /// pinning through the cross-tool naming fixture; both tests read
    /// the same file, so the two implementations cannot drift apart
    /// (the 2025.2 `_offset` -> `_r` rename had to be fixed in both
    /// independently).
    #[test]
    fn direct_offset_probe_order_follows_naming_fixture() {
        let fixture = include_str!("../../../../tapa-core/tapa-ir/testdata/naming_conventions.tsv");
        let mut checked = 0;
        for line in fixture
            .lines()
            .filter(|line| line.starts_with("direct_offset_port\t"))
        {
            let fields: Vec<&str> = line.split('\t').collect();
            let (base, candidates) = (fields[1], &fields[2..]);
            assert!(candidates.len() >= 2, "probe list needs candidates: {line}");
            // RTL declaring exactly one candidate binds that port.
            for expected in candidates {
                let rtl = vec![format!(
                    "module m({expected});\ninput [63:0] {expected};\nendmodule"
                )];
                assert_eq!(
                    direct_offset_port_name(&rtl, base),
                    *expected,
                    "line: {line}"
                );
            }
            // All candidates declared resolves in fixture probe order;
            // none declared falls back to the first spelling.
            let declarations = candidates
                .iter()
                .map(|candidate| format!("input [63:0] {candidate};"))
                .collect::<Vec<_>>()
                .join("\n");
            let rtl = vec![format!("module m();\n{declarations}\nendmodule")];
            assert_eq!(
                direct_offset_port_name(&rtl, base),
                candidates[0],
                "line: {line}"
            );
            assert_eq!(
                direct_offset_port_name(&[], base),
                candidates[0],
                "line: {line}"
            );
            checked += 1;
        }
        assert!(
            checked >= 1,
            "fixture lost its direct_offset_port production"
        );
    }
}
