#include "tapa/host/mmap.h"

#include <cstdint>

#include <type_traits>
#include <utility>
#include <vector>

#include <gtest/gtest.h>

#include "tapa/host/vec.h"

namespace tapa {
namespace {

// The tagged handles are generated by macro: four buffer-access tags across
// three single-buffer kinds, plus the sized `mmaps`. These pin the shape the
// macro is expected to produce -- in particular that `vectorized()` and
// `reinterpret()` keep the tag rather than decaying to the untagged base.

template <typename Tagged, typename Base>
void CheckTagIsPreserved() {
  static_assert(std::is_base_of<Base, Tagged>::value,
                "a tagged handle must extend its untagged kind");
  static_assert(std::is_convertible<Base, Tagged>::value,
                "a tagged handle must be constructible from its untagged kind");
}

TEST(TaggedMmapTest, EveryTagExtendsItsKind) {
  CheckTagIsPreserved<placeholder_mmap<int>, mmap<int>>();
  CheckTagIsPreserved<read_only_mmap<int>, mmap<int>>();
  CheckTagIsPreserved<write_only_mmap<int>, mmap<int>>();
  CheckTagIsPreserved<read_write_mmap<int>, mmap<int>>();

  CheckTagIsPreserved<placeholder_immap<int>, immap<int>>();
  CheckTagIsPreserved<read_only_immap<int>, immap<int>>();
  CheckTagIsPreserved<write_only_immap<int>, immap<int>>();
  CheckTagIsPreserved<read_write_immap<int>, immap<int>>();

  CheckTagIsPreserved<placeholder_ommap<int>, ommap<int>>();
  CheckTagIsPreserved<read_only_ommap<int>, ommap<int>>();
  CheckTagIsPreserved<write_only_ommap<int>, ommap<int>>();
  CheckTagIsPreserved<read_write_ommap<int>, ommap<int>>();
}

// Only the `mmap` kind is covered here. `immap`/`ommap` inherit `vectorized()`
// and `reinterpret()` from `mmap`, so those return an `mmap<U>` -- a base of
// `immap<U>`/`ommap<U>` -- and the tagged wrapper cannot convert back down.
// Instantiating e.g. `read_write_ommap<int>::reinterpret<int64_t>()` therefore
// does not compile. That predates the macro collapse (the per-kind macros
// generated the same bodies) and is simply never instantiated today.
TEST(TaggedMmapTest, VectorizedAndReinterpretKeepTheTag) {
  std::vector<int> buffer(16);

  read_only_mmap<int> ro(buffer);
  static_assert(std::is_same<decltype(ro.vectorized<2>()),
                             read_only_mmap<vec_t<int, 2>>>::value,
                "vectorized() must stay read_only");
  static_assert(std::is_same<decltype(ro.reinterpret<char>()),
                             read_only_mmap<char>>::value,
                "reinterpret() must stay read_only");

  write_only_mmap<int> wo(buffer);
  static_assert(std::is_same<decltype(wo.reinterpret<int64_t>()),
                             write_only_mmap<int64_t>>::value,
                "reinterpret() must stay write_only");

  // The generated wrappers forward to the base, so the view still describes
  // the same memory.
  EXPECT_EQ(ro.size(), buffer.size());
  EXPECT_EQ(ro.vectorized<2>().size(), buffer.size() / 2);
  EXPECT_EQ(wo.reinterpret<int64_t>().size(),
            buffer.size() * sizeof(int) / sizeof(int64_t));
}

TEST(TaggedMmapTest, SizedMmapsKeepTheTagAndTheCount) {
  static_assert(std::is_base_of<mmaps<int, 4>, read_only_mmaps<int, 4>>::value,
                "a tagged mmaps must extend its untagged kind");
  static_assert(std::is_same<decltype(std::declval<read_only_mmaps<int, 4>>()
                                          .template vectorized<2>()),
                             read_only_mmaps<vec_t<int, 2>, 4>>::value,
                "vectorized() must keep both the tag and the channel count");
}

}  // namespace
}  // namespace tapa
