"""Defining the exporter to write Verilog designs from a graph IR node."""

from functools import singledispatch

from tapa.graphir.analyses.drc_check import check_missing_wire
from tapa.graphir.types import (
    AnyModuleDefinition,
    GroupedModuleDefinition,
    ModuleParameter,
    ModulePort,
    StubModuleDefinition,
    VerilogModuleDefinition,
)
from tapa.verilog.graphir_exporter.assets.templates.grouped_module import GROUPED_MODULE
from tapa.verilog.graphir_exporter.assets.templates.module_header import MODULE_HEADER
from tapa.verilog.graphir_exporter.environment import env

TIME_SCALE = "`timescale 1 ns / 1 ps"


@singledispatch
def export_verilog_design(module: AnyModuleDefinition) -> str:
    """Return the verilog code of a module definition.

    Args:
        module (AnyModuleDefinition): The module to be exported.

    Returns:
        str: The Verilog code of the module definition.

    Examples:
        >>> module = GroupedModuleDefinition.model_validate_json(
        ...     '''{
        ...     "name": "empty_module",
        ...     "hierarchical_name": ["empty_orig_name"],
        ...     "parameters": [], "ports": [],
        ...     "module_type": "grouped_module",
        ...     "submodules": [], "wires": []}'''
        ... )
        >>> print(export_verilog_design(module))
        // ==================================================
        // RTL generated by TAPA
        //
        // Copyright 2025 RapidStream Design Automation, Inc.
        // All Rights Reserved.
        // ==================================================
        `timescale 1 ns / 1 ps
        /**   empty_orig_name   **/
        module empty_module ();
        <BLANKLINE>
        <BLANKLINE>
        <BLANKLINE>
        endmodule  // empty_module

        >>> module = VerilogModuleDefinition(
        ...     name="empty_module",
        ...     hierarchical_name=("orig_name",),
        ...     parameters=[],
        ...     ports=[],
        ...     verilog="module empty_module (); endmodule;",
        ...     submodules_module_names=(),
        ... )
        >>> print(export_verilog_design(module))
        `timescale 1 ns / 1 ps
        module empty_module (); endmodule;
    """
    msg = f"An exporter for {type(module)} is not implemented.\n"
    raise NotImplementedError(msg)  # pragma: no cover


@export_verilog_design.register
def _(module: GroupedModuleDefinition) -> str:
    return export_verilog_grouped_module(module)


@export_verilog_design.register
def _(module: VerilogModuleDefinition) -> str:
    return export_verilog_verilog_module(module)


@export_verilog_design.register
def _(module: StubModuleDefinition) -> str:  # noqa: ARG001
    return "// This stub module is excluded from exporting"


def export_verilog_grouped_module(module: GroupedModuleDefinition) -> str:
    """Return the Verilog code of a grouped module definition."""
    check_missing_wire(module)

    template = env.from_string(GROUPED_MODULE)
    return template.render(module=module)


def export_verilog_verilog_module(module: VerilogModuleDefinition) -> str:
    """Return the verilog code of a verilog leaf module definition.

    Args:
        module (GroupedModuleDefinition): The module to be exported.

    Returns:
        str: The Verilog code of the verilog module definition.

    Examples:
        >>> print(
        ...     export_verilog_verilog_module(
        ...         VerilogModuleDefinition(
        ...             name="empty_module",
        ...             hierarchical_name=None,
        ...             parameters=[],
        ...             ports=[],
        ...             verilog="module empty_module; endmodule;",
        ...             submodules_module_names=(),
        ...         )
        ...     )
        ... )
        `timescale 1 ns / 1 ps
        module empty_module; endmodule;
    """
    return (
        TIME_SCALE + "\n" + module.verilog
        if TIME_SCALE not in module.verilog
        else module.verilog
    )


def export_verilog_header(
    name: str,
    parameters: tuple[ModuleParameter, ...],
    ports: tuple[ModulePort, ...],
) -> str:
    """Return the verilog code of a tuple of port definitions.

    Args:
        name (str): The name of the module.
        parameters (tuple[ModuleParameter, ...]): The parameters of the module.
        ports (tuple[ModulePort, ...]): The ports of the module.

    Returns:
        str: The exported header ports tuple.

    Examples:
        >>> parameters = [
        ...     ModuleParameter.model_validate_json(
        ...         '''
        ...     {"name": "DEPTH", "hierarchical_name": ["D"],
        ...      "expr": [{"type": "lit", "repr": "16"}]}'''
        ...     )
        ... ]
        >>> ports = [
        ...     ModulePort.model_validate_json(
        ...         '''
        ...     {"name": "test1", "hierarchical_name": ["test1"], "type": "input wire",
        ...          "range": {"left": [{"type": "lit", "repr": "31"}],
        ...                    "right": [{"type": "lit", "repr": "0"}]}}'''
        ...     ),
        ...     ModulePort.model_validate_json(
        ...         '''
        ...     {"name": "test2", "hierarchical_name": ["T2"], "type": "output reg",
        ...          "range": {"left": [{"type": "lit", "repr": "1"}],
        ...                    "right": [{"type": "lit", "repr": "0"}]}}'''
        ...     ),
        ... ]
        >>> print(export_verilog_header("test", parameters, ports))
        module test #(
            /**   D   **/
            parameter DEPTH = 16
        ) (
            input wire [31:0] test1,
            /**   T2   **/
            output reg [ 1:0] test2
        );
    """
    template = env.from_string(MODULE_HEADER)
    return template.render(name=name, parameters=parameters, ports=ports)
