"""Tests for tapa/verilog/graphir_exporter/verilog.py."""

from tapa.graphir.types import GroupedModuleDefinition
from tapa.verilog.graphir_exporter.verilog import export_verilog_grouped_module

_NESTING_MODULE_JSON = """{
    "name": "nesting_module",
    "hierarchical_name": ["orig_1"],
    "parameters": [
        {"name": "DEPTH", "hierarchical_name": ["orig_2", "D"],
         "expr": [{"type": "lit", "repr": "16"}]}],
    "ports": [
        {"name": "test_in", "hierarchical_name": [],
         "type": "input wire",
         "range": {"left": [{"type": "lit", "repr": "31"}],
                   "right": [{"type": "lit", "repr": "0"}]}},
        {"name": "test_out", "hierarchical_name": ["test_out"],
         "type": "output wire", "range": null}],
    "module_type": "grouped_module",
    "submodules": [{
        "name": "submodule1",
        "hierarchical_name": ["submodule1"],
        "module": "nested_module",
        "connections": [
            {"name": "p1", "hierarchical_name": ["orig_6"],
             "expr": [{"type": "id", "repr": "test_in"}]},
            {"name": "p2", "hierarchical_name": ["p2"],
             "expr": [{"type": "id", "repr": "test_wire"}]}],
        "parameters": [], "floorplan_region": null, "area": null
    }, {
        "name": "submodule2",
        "hierarchical_name": ["orig_8"],
        "module": "nested_module",
        "connections": [
            {"name": "p1", "hierarchical_name": ["orig_9"],
             "expr": [{"type": "id", "repr": "test_wire"}]},
            {"name": "p2", "hierarchical_name": ["orig_10"],
             "expr": [{"type": "id", "repr": "test_out"}]}],
        "parameters": [{"name": "TEST", "hierarchical_name": ["TEST"],
                        "expr": [{"type": "lit", "repr": "1"}]},
                       {"name": "D", "hierarchical_name": ["orig_12"],
                        "expr": [{"type": "id", "repr": "DEPTH"}]}],
        "floorplan_region": null, "area": null
    }],
    "wires": [
      {
        "name": "test_wire",
        "hierarchical_name": ["orig_13"],
        "range": null
      },
      {"name": "unused_wire", "hierarchical_name": ["unused_wire"],
       "range": {"left": [{"type": "lit", "repr": "31"}],
                 "right": [{"type": "lit", "repr": "0"}]}}]}"""

_EXPECTED_NESTING_MODULE_OUTPUT = (
    "\n\n"
    "// ==================================================\n"
    "// RTL generated by TAPA\n"
    "//\n"
    "// Copyright 2025 RapidStream Design Automation, Inc.\n"
    "// All Rights Reserved.\n"
    "// ==================================================\n"
    "`timescale 1 ns / 1 ps\n"
    "\n\n"
    "/**   orig_1   **/\n"
    "module nesting_module #(\n"
    "    /**   orig_2/D   **/\n"
    "    parameter DEPTH = 16\n"
    ") (\n"
    "    input wire  [31:0] test_in,\n"
    "    output wire        test_out\n"
    ");\n"
    "\n\n\n"
    "/**   orig_13   **/\n"
    "wire        test_wire;\n"
    "wire [31:0] unused_wire;\n"
    "\n\n\n\n\n\n\n"
    "nested_module submodule1 (\n"
    "    /**   orig_6   **/\n"
    "    .p1 (test_in),\n"
    "    .p2 (test_wire)\n"
    ");\n"
    "\n\n"
    "nested_module #(\n"
    "    /**   orig_12   **/\n"
    "    .D    (DEPTH),\n"
    "    .TEST (1)\n"
    ") submodule2 /**   orig_8   **/ (\n"
    "    /**   orig_9   **/\n"
    "    .p1 (test_wire),\n"
    "    /**   orig_10   **/\n"
    "    .p2 (test_out)\n"
    ");\n"
    "\n\n\n"
    "endmodule  // nesting_module\n"
)


def test_export_verilog_grouped_module_nesting_module() -> None:
    """Lock in the full Verilog output format for a two-submodule grouped module."""
    module = GroupedModuleDefinition.model_validate_json(_NESTING_MODULE_JSON)
    result = export_verilog_grouped_module(module)
    assert result == _EXPECTED_NESTING_MODULE_OUTPUT
