// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Mmap2Stream_Mmap2Stream_Pipeline_VITIS_LOOP_27_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_mmap_0_AWVALID,
        m_axi_mmap_0_AWREADY,
        m_axi_mmap_0_AWADDR,
        m_axi_mmap_0_AWID,
        m_axi_mmap_0_AWLEN,
        m_axi_mmap_0_AWSIZE,
        m_axi_mmap_0_AWBURST,
        m_axi_mmap_0_AWLOCK,
        m_axi_mmap_0_AWCACHE,
        m_axi_mmap_0_AWPROT,
        m_axi_mmap_0_AWQOS,
        m_axi_mmap_0_AWREGION,
        m_axi_mmap_0_AWUSER,
        m_axi_mmap_0_WVALID,
        m_axi_mmap_0_WREADY,
        m_axi_mmap_0_WDATA,
        m_axi_mmap_0_WSTRB,
        m_axi_mmap_0_WLAST,
        m_axi_mmap_0_WID,
        m_axi_mmap_0_WUSER,
        m_axi_mmap_0_ARVALID,
        m_axi_mmap_0_ARREADY,
        m_axi_mmap_0_ARADDR,
        m_axi_mmap_0_ARID,
        m_axi_mmap_0_ARLEN,
        m_axi_mmap_0_ARSIZE,
        m_axi_mmap_0_ARBURST,
        m_axi_mmap_0_ARLOCK,
        m_axi_mmap_0_ARCACHE,
        m_axi_mmap_0_ARPROT,
        m_axi_mmap_0_ARQOS,
        m_axi_mmap_0_ARREGION,
        m_axi_mmap_0_ARUSER,
        m_axi_mmap_0_RVALID,
        m_axi_mmap_0_RREADY,
        m_axi_mmap_0_RDATA,
        m_axi_mmap_0_RLAST,
        m_axi_mmap_0_RID,
        m_axi_mmap_0_RFIFONUM,
        m_axi_mmap_0_RUSER,
        m_axi_mmap_0_RRESP,
        m_axi_mmap_0_BVALID,
        m_axi_mmap_0_BREADY,
        m_axi_mmap_0_BRESP,
        m_axi_mmap_0_BID,
        m_axi_mmap_0_BUSER,
        stream_s_din,
        stream_s_full_n,
        stream_s_write,
        n,
        sext_ln27
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_mmap_0_AWVALID;
input   m_axi_mmap_0_AWREADY;
output  [63:0] m_axi_mmap_0_AWADDR;
output  [0:0] m_axi_mmap_0_AWID;
output  [31:0] m_axi_mmap_0_AWLEN;
output  [2:0] m_axi_mmap_0_AWSIZE;
output  [1:0] m_axi_mmap_0_AWBURST;
output  [1:0] m_axi_mmap_0_AWLOCK;
output  [3:0] m_axi_mmap_0_AWCACHE;
output  [2:0] m_axi_mmap_0_AWPROT;
output  [3:0] m_axi_mmap_0_AWQOS;
output  [3:0] m_axi_mmap_0_AWREGION;
output  [0:0] m_axi_mmap_0_AWUSER;
output   m_axi_mmap_0_WVALID;
input   m_axi_mmap_0_WREADY;
output  [31:0] m_axi_mmap_0_WDATA;
output  [3:0] m_axi_mmap_0_WSTRB;
output   m_axi_mmap_0_WLAST;
output  [0:0] m_axi_mmap_0_WID;
output  [0:0] m_axi_mmap_0_WUSER;
output   m_axi_mmap_0_ARVALID;
input   m_axi_mmap_0_ARREADY;
output  [63:0] m_axi_mmap_0_ARADDR;
output  [0:0] m_axi_mmap_0_ARID;
output  [31:0] m_axi_mmap_0_ARLEN;
output  [2:0] m_axi_mmap_0_ARSIZE;
output  [1:0] m_axi_mmap_0_ARBURST;
output  [1:0] m_axi_mmap_0_ARLOCK;
output  [3:0] m_axi_mmap_0_ARCACHE;
output  [2:0] m_axi_mmap_0_ARPROT;
output  [3:0] m_axi_mmap_0_ARQOS;
output  [3:0] m_axi_mmap_0_ARREGION;
output  [0:0] m_axi_mmap_0_ARUSER;
input   m_axi_mmap_0_RVALID;
output   m_axi_mmap_0_RREADY;
input  [31:0] m_axi_mmap_0_RDATA;
input   m_axi_mmap_0_RLAST;
input  [0:0] m_axi_mmap_0_RID;
input  [8:0] m_axi_mmap_0_RFIFONUM;
input  [0:0] m_axi_mmap_0_RUSER;
input  [1:0] m_axi_mmap_0_RRESP;
input   m_axi_mmap_0_BVALID;
output   m_axi_mmap_0_BREADY;
input  [1:0] m_axi_mmap_0_BRESP;
input  [0:0] m_axi_mmap_0_BID;
input  [0:0] m_axi_mmap_0_BUSER;
output  [32:0] stream_s_din;
input   stream_s_full_n;
output   stream_s_write;
input  [63:0] n;
input  [61:0] sext_ln27;

reg ap_idle;
reg m_axi_mmap_0_RREADY;
reg stream_s_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln27_fu_88_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    mmap_blk_n_R;
wire    ap_block_pp0_stage0_grp1;
reg    stream_s_blk_n;
reg    ap_block_pp0_stage0_11001;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [31:0] mmap_addr_read_reg_135;
reg   [63:0] i_fu_48;
wire   [63:0] i_1_fu_93_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_01001_grp1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 i_fu_48 = 64'd0;
#0 ap_done_reg = 1'b0;
end

Mmap2Stream_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_48 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln27_fu_88_p2 == 1'd0))) begin
            i_fu_48 <= i_1_fu_93_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        mmap_addr_read_reg_135 <= m_axi_mmap_0_RDATA;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln27_fu_88_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_mmap_0_RREADY = 1'b1;
    end else begin
        m_axi_mmap_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        mmap_blk_n_R = m_axi_mmap_0_RVALID;
    end else begin
        mmap_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        stream_s_blk_n = stream_s_full_n;
    end else begin
        stream_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        stream_s_write = 1'b1;
    end else begin
        stream_s_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = (((stream_s_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((m_axi_mmap_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((stream_s_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((m_axi_mmap_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((stream_s_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((m_axi_mmap_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((stream_s_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((m_axi_mmap_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign i_1_fu_93_p2 = (i_fu_48 + 64'd1);

assign icmp_ln27_fu_88_p2 = ((i_fu_48 == n) ? 1'b1 : 1'b0);

assign m_axi_mmap_0_ARADDR = 64'd0;

assign m_axi_mmap_0_ARBURST = 2'd0;

assign m_axi_mmap_0_ARCACHE = 4'd0;

assign m_axi_mmap_0_ARID = 1'd0;

assign m_axi_mmap_0_ARLEN = 32'd0;

assign m_axi_mmap_0_ARLOCK = 2'd0;

assign m_axi_mmap_0_ARPROT = 3'd0;

assign m_axi_mmap_0_ARQOS = 4'd0;

assign m_axi_mmap_0_ARREGION = 4'd0;

assign m_axi_mmap_0_ARSIZE = 3'd0;

assign m_axi_mmap_0_ARUSER = 1'd0;

assign m_axi_mmap_0_ARVALID = 1'b0;

assign m_axi_mmap_0_AWADDR = 64'd0;

assign m_axi_mmap_0_AWBURST = 2'd0;

assign m_axi_mmap_0_AWCACHE = 4'd0;

assign m_axi_mmap_0_AWID = 1'd0;

assign m_axi_mmap_0_AWLEN = 32'd0;

assign m_axi_mmap_0_AWLOCK = 2'd0;

assign m_axi_mmap_0_AWPROT = 3'd0;

assign m_axi_mmap_0_AWQOS = 4'd0;

assign m_axi_mmap_0_AWREGION = 4'd0;

assign m_axi_mmap_0_AWSIZE = 3'd0;

assign m_axi_mmap_0_AWUSER = 1'd0;

assign m_axi_mmap_0_AWVALID = 1'b0;

assign m_axi_mmap_0_BREADY = 1'b0;

assign m_axi_mmap_0_WDATA = 32'd0;

assign m_axi_mmap_0_WID = 1'd0;

assign m_axi_mmap_0_WLAST = 1'b0;

assign m_axi_mmap_0_WSTRB = 4'd0;

assign m_axi_mmap_0_WUSER = 1'd0;

assign m_axi_mmap_0_WVALID = 1'b0;

assign stream_s_din = mmap_addr_read_reg_135;

endmodule //Mmap2Stream_Mmap2Stream_Pipeline_VITIS_LOOP_27_1
