//! Verilog emission for `GraphIR` module definitions.

use std::fmt::Write;

use tapa_graphir::{
    AnyModuleDefinition, BaseFields, Expression, GroupedFields, HierarchicalName,
    ModuleConnection, ModuleInstantiation, ModuleNet, ModuleParameter, ModulePort, Range,
    VerilogFields,
};

const TIMESCALE: &str = "`timescale 1 ns / 1 ps";
const COMMON_HEADER: &str = "\
// ==================================================
// RTL generated by TAPA
//
// Copyright 2025 RapidStream Design Automation, Inc.
// All Rights Reserved.
// ==================================================";

/// Render any module definition variant to Verilog source.
#[must_use]
pub fn render_module(module: &AnyModuleDefinition) -> String {
    match module {
        AnyModuleDefinition::Grouped { base, grouped, .. }
        | AnyModuleDefinition::InternalGrouped { base, grouped, .. } => {
            render_grouped(base, grouped)
        }

        AnyModuleDefinition::Verilog { base, verilog, .. }
        | AnyModuleDefinition::PassThrough { base, verilog, .. }
        | AnyModuleDefinition::Aux { base, verilog, .. }
        | AnyModuleDefinition::AuxSplit { base, verilog, .. }
        | AnyModuleDefinition::InternalVerilog { base, verilog, .. } => {
            render_verilog_module(base, verilog)
        }

        AnyModuleDefinition::Stub { .. } => {
            "// This stub module is excluded from exporting".to_owned()
        }
    }
}

/// Render a grouped module to formatted Verilog.
fn render_grouped(base: &BaseFields, grouped: &GroupedFields) -> String {
    let mut out = String::with_capacity(4096);

    // Common header
    writeln!(out, "{COMMON_HEADER}").unwrap();
    writeln!(out, "{TIMESCALE}").unwrap();
    out.push('\n');

    // Hierarchical name comment
    write_hierarchical_comment(&mut out, &base.hierarchical_name, &base.name);
    out.push('\n');

    // Module header
    write!(out, "module {}", base.name).unwrap();

    // Parameters
    if !base.parameters.is_empty() {
        writeln!(out, " #(").unwrap();
        write_parameters(&mut out, &base.parameters);
        write!(out, ")").unwrap();
    }

    // Ports
    writeln!(out, " (").unwrap();
    if !base.ports.is_empty() {
        write_ports(&mut out, &base.ports);
    }
    writeln!(out, ");").unwrap();

    // Wires
    if !grouped.wires.is_empty() {
        out.push('\n');
        write_wires(&mut out, &grouped.wires);
    }

    // Submodule instantiations
    for inst in &grouped.submodules {
        out.push('\n');
        write_instantiation(&mut out, inst);
    }

    // Footer
    writeln!(out).unwrap();
    writeln!(out, "endmodule  // {}", base.name).unwrap();
    out
}

/// Render a raw Verilog module (prepend timescale if needed).
fn render_verilog_module(_base: &BaseFields, verilog: &VerilogFields) -> String {
    if verilog.verilog.contains(TIMESCALE) {
        verilog.verilog.clone()
    } else {
        format!("{TIMESCALE}\n{}", verilog.verilog)
    }
}

/// Write hierarchical name comment if applicable.
fn write_hierarchical_comment(out: &mut String, hname: &HierarchicalName, name: &str) {
    if hname.is_none() {
        writeln!(out, "/**   Generated by TAPA   **/").unwrap();
    } else if let Some(parts) = hname.as_parts() {
        if !parts.is_empty() {
            let hname_str = parts.join("/");
            if hname_str != name {
                writeln!(out, "/**   {hname_str}   **/").unwrap();
            }
        }
    }
}

/// Write module parameters in `parameter [range] name = expr` format.
fn write_parameters(out: &mut String, params: &[ModuleParameter]) {
    let max_name = params.iter().map(|p| p.name.len()).max().unwrap_or(0);
    let max_range = params
        .iter()
        .map(|p| range_str(p.range.as_ref()).len())
        .max()
        .unwrap_or(0);

    for (i, param) in params.iter().enumerate() {
        write_hierarchical_comment_inline(out, &param.hierarchical_name, &param.name);
        write!(out, "    parameter ").unwrap();
        write_range_aligned(out, param.range.as_ref(), max_range);
        write!(out, "{:width$}", param.name, width = max_name).unwrap();
        if !param.expr.is_empty() {
            write!(out, " = {}", format_expr(&param.expr)).unwrap();
        }
        if i < params.len() - 1 {
            out.push(',');
        }
        out.push('\n');
    }
}

/// Write module ports in `type [range] name` format.
fn write_ports(out: &mut String, ports: &[ModulePort]) {
    let max_type = ports.iter().map(|p| p.port_type.len()).max().unwrap_or(0);
    let max_range = ports
        .iter()
        .map(|p| range_str(p.range.as_ref()).len())
        .max()
        .unwrap_or(0);

    for (i, port) in ports.iter().enumerate() {
        write_hierarchical_comment_inline(out, &port.hierarchical_name, &port.name);
        write!(out, "    {:width$} ", port.port_type, width = max_type).unwrap();
        write_range_aligned(out, port.range.as_ref(), max_range);
        write!(out, "{}", port.name).unwrap();
        if i < ports.len() - 1 {
            out.push(',');
        }
        out.push('\n');
    }
}

/// Write wire declarations.
fn write_wires(out: &mut String, wires: &[ModuleNet]) {
    let max_range = wires
        .iter()
        .map(|w| range_str(w.range.as_ref()).len())
        .max()
        .unwrap_or(0);

    for wire in wires {
        write_hierarchical_comment_inline(out, &wire.hierarchical_name, &wire.name);
        write!(out, "wire ").unwrap();
        write_range_aligned(out, wire.range.as_ref(), max_range);
        writeln!(out, "{};", wire.name).unwrap();
    }
}

/// Write a submodule instantiation.
fn write_instantiation(out: &mut String, inst: &ModuleInstantiation) {
    // Pragma string (if any)
    for (key, val) in &inst.pragmas {
        writeln!(out, "(* {key} = \"{val}\" *)").unwrap();
    }

    // Module name
    write!(out, "{}", inst.module).unwrap();

    // Parameters
    if !inst.parameters.is_empty() {
        writeln!(out, " #(").unwrap();
        write_connections(&mut *out, &inst.parameters);
        write!(out, ")").unwrap();
    }

    // Instance name
    write!(out, " {}", inst.name).unwrap();

    // Hierarchical name comment
    write_hierarchical_comment_inline_no_newline(out, &inst.hierarchical_name, &inst.name);

    // Connections
    writeln!(out, " (").unwrap();
    if !inst.connections.is_empty() {
        write_connections(&mut *out, &inst.connections);
    }
    writeln!(out, ");").unwrap();
}

/// Write connections (used for both parameters and port connections).
fn write_connections(out: &mut String, conns: &[ModuleConnection]) {
    let max_name = conns.iter().map(|c| c.name.len()).max().unwrap_or(0);

    for (i, conn) in conns.iter().enumerate() {
        write_hierarchical_comment_inline(out, &conn.hierarchical_name, &conn.name);
        write!(
            out,
            "    .{:width$} ({})",
            conn.name,
            format_expr(&conn.expr),
            width = max_name
        )
        .unwrap();
        if i < conns.len() - 1 {
            out.push(',');
        }
        out.push('\n');
    }
}

/// Write hierarchical name comment on its own line (indented).
fn write_hierarchical_comment_inline(out: &mut String, hname: &HierarchicalName, name: &str) {
    if let Some(parts) = hname.as_parts() {
        if !parts.is_empty() {
            let hname_str = parts.join("/");
            if hname_str != name {
                writeln!(out, "    /**   {hname_str}   **/").unwrap();
            }
        }
    }
}

/// Write hierarchical name comment inline (no newline, for instance names).
fn write_hierarchical_comment_inline_no_newline(
    out: &mut String,
    hname: &HierarchicalName,
    name: &str,
) {
    if hname.is_none() {
        write!(out, " /**   Generated by TAPA   **/").unwrap();
    } else if let Some(parts) = hname.as_parts() {
        if !parts.is_empty() {
            let hname_str = parts.join("/");
            if hname_str != name {
                write!(out, " /**   {hname_str}   **/").unwrap();
            }
        }
    }
}

/// Format a range as `[left:right]` or empty string.
fn range_str(range: Option<&Range>) -> String {
    match range {
        Some(r) => format!("[{}:{}]", format_expr(&r.left), format_expr(&r.right)),
        None => String::new(),
    }
}

/// Write range aligned to `max_range` width.
fn write_range_aligned(out: &mut String, range: Option<&Range>, max_range: usize) {
    let rs = range_str(range);
    if rs.is_empty() {
        if max_range > 0 {
            write!(out, "{:width$} ", "", width = max_range).unwrap();
        }
    } else {
        write!(out, "{rs:>max_range$} ").unwrap();
    }
}

/// Format an expression as a string (concatenating token reprs).
fn format_expr(expr: &Expression) -> String {
    expr.tokens().iter().map(|t| t.repr.as_str()).collect::<Vec<_>>().join(" ")
}

/// DRC: check that all identifiers used in submodule connections are defined.
pub fn check_missing_wire(base: &BaseFields, grouped: &GroupedFields) -> Vec<String> {
    let mut defined = std::collections::HashSet::new();
    for wire in &grouped.wires {
        defined.insert(wire.name.as_str());
    }
    for port in &base.ports {
        defined.insert(port.name.as_str());
    }
    for param in &base.parameters {
        defined.insert(param.name.as_str());
    }

    let mut missing = Vec::new();
    for inst in &grouped.submodules {
        for conn in &inst.connections {
            for id in conn.expr.get_used_identifiers() {
                if !defined.contains(id) && !missing.contains(&id.to_owned()) {
                    missing.push(id.to_owned());
                }
            }
        }
    }
    missing.sort();
    missing
}

#[cfg(test)]
mod tests {
    use super::*;
    use tapa_graphir::{Expression, HierarchicalName, Token};

    #[test]
    fn format_expr_single_token() {
        let e = Expression::new_id("foo");
        assert_eq!(format_expr(&e), "foo");
    }

    #[test]
    fn format_expr_multi_token() {
        let e = Expression(vec![
            Token::new_id("a"),
            Token::new_lit("+"),
            Token::new_id("b"),
        ]);
        assert_eq!(format_expr(&e), "a + b");
    }

    #[test]
    fn render_stub_is_comment() {
        let stub = AnyModuleDefinition::new_stub("fifo".into(), Vec::new());
        let out = render_module(&stub);
        assert_eq!(out, "// This stub module is excluded from exporting");
    }

    #[test]
    fn render_grouped_basic() {
        let module = AnyModuleDefinition::new_grouped(
            "top_mod".into(),
            vec![
                ModulePort {
                    name: "clk".into(),
                    hierarchical_name: HierarchicalName::none(),
                    port_type: "input wire".into(),
                    range: None,
                    extra: std::collections::BTreeMap::default(),
                },
                ModulePort {
                    name: "data_out".into(),
                    hierarchical_name: HierarchicalName::none(),
                    port_type: "output wire".into(),
                    range: Some(Range {
                        left: Expression::new_lit("31"),
                        right: Expression::new_lit("0"),
                    }),
                    extra: std::collections::BTreeMap::default(),
                },
            ],
            Vec::new(),
            vec![ModuleNet {
                name: "internal_sig".into(),
                hierarchical_name: HierarchicalName::none(),
                range: None,
                extra: std::collections::BTreeMap::default(),
            }],
        );
        let out = render_module(&module);
        assert!(out.contains("module top_mod"), "got:\n{out}");
        assert!(out.contains("input wire"), "got:\n{out}");
        assert!(out.contains("output wire"), "got:\n{out}");
        assert!(out.contains("[31:0]"), "got:\n{out}");
        assert!(out.contains("wire"), "got:\n{out}");
        assert!(out.contains("internal_sig"), "got:\n{out}");
        assert!(out.contains("endmodule  // top_mod"), "got:\n{out}");
        assert!(out.contains(TIMESCALE), "got:\n{out}");
    }

    #[test]
    fn render_verilog_prepends_timescale() {
        let module = AnyModuleDefinition::new_verilog(
            "leaf".into(),
            Vec::new(),
            "module leaf(); endmodule".into(),
        );
        let out = render_module(&module);
        assert!(out.starts_with(TIMESCALE), "should prepend timescale, got:\n{out}");
        assert!(out.contains("module leaf"), "got:\n{out}");
    }

    #[test]
    fn render_verilog_no_duplicate_timescale() {
        let src = format!("{TIMESCALE}\nmodule leaf(); endmodule");
        let module = AnyModuleDefinition::new_verilog("leaf".into(), Vec::new(), src);
        let out = render_module(&module);
        // Should not have double timescale
        assert_eq!(out.matches(TIMESCALE).count(), 1, "got:\n{out}");
    }

    #[test]
    fn render_grouped_with_submodule() {
        let module = AnyModuleDefinition::new_grouped(
            "parent".into(),
            vec![ModulePort {
                name: "clk".into(),
                hierarchical_name: HierarchicalName::none(),
                port_type: "input wire".into(),
                range: None,
                extra: std::collections::BTreeMap::default(),
            }],
            vec![ModuleInstantiation {
                name: "child_0".into(),
                hierarchical_name: HierarchicalName::none(),
                module: "child_mod".into(),
                connections: vec![ModuleConnection {
                    name: "clk".into(),
                    hierarchical_name: HierarchicalName::none(),
                    expr: Expression::new_id("clk"),
                    extra: std::collections::BTreeMap::default(),
                }],
                parameters: Vec::new(),
                floorplan_region: None,
                area: None,
                pragmas: Vec::new(),
                extra: std::collections::BTreeMap::default(),
            }],
            Vec::new(),
        );
        let out = render_module(&module);
        assert!(out.contains("child_mod"), "got:\n{out}");
        assert!(out.contains("child_0"), "got:\n{out}");
        assert!(out.contains(".clk (clk)"), "got:\n{out}");
    }

    #[test]
    fn check_missing_wire_finds_undefined() {
        let base = BaseFields {
            name: "mod".into(),
            hierarchical_name: HierarchicalName::none(),
            parameters: Vec::new(),
            ports: vec![ModulePort {
                name: "clk".into(),
                hierarchical_name: HierarchicalName::none(),
                port_type: "input wire".into(),
                range: None,
                extra: std::collections::BTreeMap::default(),
            }],
            metadata: None,
        };
        let grouped = GroupedFields {
            submodules: vec![ModuleInstantiation {
                name: "inst".into(),
                hierarchical_name: HierarchicalName::none(),
                module: "child".into(),
                connections: vec![ModuleConnection {
                    name: "sig".into(),
                    hierarchical_name: HierarchicalName::none(),
                    expr: Expression::new_id("undefined_wire"),
                    extra: std::collections::BTreeMap::default(),
                }],
                parameters: Vec::new(),
                floorplan_region: None,
                area: None,
                pragmas: Vec::new(),
                extra: std::collections::BTreeMap::default(),
            }],
            wires: Vec::new(),
        };
        let missing = check_missing_wire(&base, &grouped);
        assert_eq!(missing, vec!["undefined_wire"]);
    }

    #[test]
    fn check_missing_wire_all_defined() {
        let base = BaseFields {
            name: "mod".into(),
            hierarchical_name: HierarchicalName::none(),
            parameters: Vec::new(),
            ports: vec![ModulePort {
                name: "clk".into(),
                hierarchical_name: HierarchicalName::none(),
                port_type: "input wire".into(),
                range: None,
                extra: std::collections::BTreeMap::default(),
            }],
            metadata: None,
        };
        let grouped = GroupedFields {
            submodules: vec![ModuleInstantiation {
                name: "inst".into(),
                hierarchical_name: HierarchicalName::none(),
                module: "child".into(),
                connections: vec![ModuleConnection {
                    name: "clk_in".into(),
                    hierarchical_name: HierarchicalName::none(),
                    expr: Expression::new_id("clk"),
                    extra: std::collections::BTreeMap::default(),
                }],
                parameters: Vec::new(),
                floorplan_region: None,
                area: None,
                pragmas: Vec::new(),
                extra: std::collections::BTreeMap::default(),
            }],
            wires: Vec::new(),
        };
        let missing = check_missing_wire(&base, &grouped);
        assert!(missing.is_empty(), "should be empty, got: {missing:?}");
    }
}
