//! TAPA protocol constants.
//!
//! Single source of truth for handshake, stream, FIFO, and M-AXI naming
//! conventions shared across the TAPA toolchain.

// ── Handshake port names ────────────────────────────────────────────

pub const HANDSHAKE_CLK: &str = "ap_clk";
/// Active-high reset generated by TAPA codegen
/// (`assign ap_rst = ~ap_rst_n`).
pub const HANDSHAKE_RST: &str = "ap_rst";
/// Vitis-HLS-internal inverted reset. TAPA never generates this name;
/// it is recognized and stripped from HLS output.
pub const HLS_RST_INV: &str = "ap_rst_n_inv";
pub const HANDSHAKE_RST_N: &str = "ap_rst_n";
pub const HANDSHAKE_START: &str = "ap_start";
pub const HANDSHAKE_DONE: &str = "ap_done";
pub const HANDSHAKE_IDLE: &str = "ap_idle";
pub const HANDSHAKE_READY: &str = "ap_ready";

// ── HLS-internal artifacts stripped by RTL cleanup ──────────────────

/// Clock-enable register emitted by Vitis HLS for multi-cycle blocks.
pub const HLS_CE_REG: &str = "ap_ce_reg";
/// FSM current-state register.
pub const HLS_FSM_CS: &str = "ap_CS_fsm";
/// FSM next-state register.
pub const HLS_FSM_NS: &str = "ap_NS_fsm";
/// FSM per-state parameter/signal name prefix (`ap_ST_fsm_state<N>`).
pub const HLS_FSM_STATE_PREFIX: &str = "ap_ST_fsm_state";

// ── Stream port suffixes ────────────────────────────────────────────

pub const ISTREAM_SUFFIXES: &[&str] = &["_dout", "_empty_n", "_read"];
pub const OSTREAM_SUFFIXES: &[&str] = &["_din", "_full_n", "_write"];
pub const STREAM_DATA_SUFFIXES: &[&str] = &["_dout", "_din"];

/// Width of a stream's data wire for a given element width; the stream
/// payload is widened by one bit.
pub const fn stream_data_wire_width(elem_width: u32) -> u32 {
    elem_width.saturating_add(1)
}

/// Scalar-stream data/flow port name: `{base}_s{suffix}`.
#[must_use]
pub fn stream_port_name(base: &str, suffix: &str) -> String {
    format!("{base}_s{suffix}")
}

/// Scalar-stream peek port name: `{base}_peek{suffix}`; an empty `suffix`
/// names the ostream peek port.
#[must_use]
pub fn stream_peek_port_name(base: &str, suffix: &str) -> String {
    format!("{base}_peek{suffix}")
}

/// Port-name suffix → wire direction (`"input"` or `"output"`).
pub static STREAM_PORT_DIRECTION: phf::Map<&'static str, &'static str> = phf::phf_map! {
    "_dout" => "input",
    "_empty_n" => "input",
    "_read" => "output",
    "_din" => "output",
    "_full_n" => "input",
    "_write" => "output",
};

// ── FIFO interface ports ────────────────────────────────────────────

pub const FIFO_READ_PORTS: &[&str] = &["if_dout", "if_empty_n", "if_read", "if_read_ce"];
pub const FIFO_WRITE_PORTS: &[&str] = &["if_din", "if_full_n", "if_write", "if_write_ce"];

// ── AXI naming prefixes ─────────────────────────────────────────────

pub const S_AXI_NAME: &str = "s_axi_control";

/// AXI-Lite control port names (without the `s_axi_control_` prefix),
/// as exposed by the HLS-generated top-level control interface.
pub const S_AXI_LITE_CTRL_PORTS: &[&str] = &[
    "AWVALID", "AWREADY", "AWADDR", "WVALID", "WREADY", "WDATA", "WSTRB", "ARVALID", "ARREADY",
    "ARADDR", "RVALID", "RREADY", "RDATA", "RRESP", "BVALID", "BREADY", "BRESP",
];

pub const M_AXI_PREFIX: &str = "m_axi_";

/// Canonical M-AXI channel emission order.
pub const M_AXI_CHANNEL_ORDER: &[&str] = &["AR", "AW", "B", "R", "W"];

// ── M-AXI default parameters ───────────────────────────────────────

/// Default AXI address width in bits: the `m_axi` address bus width
/// produced by HLS and assumed throughout TAPA's generated fabric.
pub const AXI_ADDR_WIDTH: u32 = 64;

/// Default AXI ID width in bits of a port driven directly by an HLS
/// child; TAPA widens IDs only at crossbars for thread routing.
pub const AXI_ID_WIDTH: u32 = 1;

/// Outstanding-transaction budget baked into the generated AXI
/// crossbar wrapper.
///
/// It parameterises both the per-channel `M<idx>_ISSUE` parameter and
/// the per-slave `S_ACCEPT` acceptance count. 16 mirrors the
/// `S_ACCEPT` default of the vendored `axi_crossbar.v`; TAPA applies
/// the same budget to issue tracking.
pub const M_AXI_MAX_OUTSTANDING: u32 = 16;

// ── M-AXI port widths ───────────────────────────────────────────────

/// Default bit width for each M-AXI sub-port.  `0` means the width is
/// parameterised (ADDR, DATA) or derived (STRB = DATA / 8).
pub static M_AXI_PORT_WIDTHS: phf::Map<&'static str, u32> = phf::phf_map! {
    "ADDR" => 0,
    "BURST" => 2,
    "CACHE" => 4,
    "DATA" => 0,
    "ID" => 1,
    "LAST" => 1,
    "LEN" => 8,
    "LOCK" => 1,
    "PROT" => 3,
    "QOS" => 4,
    "READY" => 1,
    "RESP" => 2,
    "SIZE" => 3,
    "STRB" => 0,
    "VALID" => 1,
};

/// Resolve the bit width of an M-AXI sub-port.
///
/// `data_width`, `addr_width`, `id_width` supply the parameterised
/// widths (DATA/ADDR/ID). STRB is derived as `ceil(data_width / 8)`.
/// All other sub-ports use their fixed default from [`M_AXI_PORT_WIDTHS`].
#[must_use]
pub fn axi_subport_width(subport: &str, data_width: u32, addr_width: u32, id_width: u32) -> u32 {
    let default = M_AXI_PORT_WIDTHS.get(subport).copied().unwrap_or(1);
    match subport {
        "ADDR" => addr_width,
        "DATA" => data_width,
        "ID" => id_width,
        "STRB" => data_width.div_ceil(8),
        _ if default == 0 => 1,
        _ => default,
    }
}

/// Extract the sub-port name from an M-AXI signal suffix:
/// `_ARADDR` → `ADDR`, `_RDATA` → `DATA`, `_BRESP` → `RESP`.
/// Unknown suffixes are returned with channel prefixes and leading
/// underscores stripped.
#[must_use]
pub fn axi_subport_from_suffix(suffix: &str) -> &str {
    let s = suffix.trim_start_matches('_');
    s.strip_prefix("AR")
        .or_else(|| s.strip_prefix("AW"))
        .or_else(|| s.strip_prefix('R'))
        .or_else(|| s.strip_prefix('W'))
        .or_else(|| s.strip_prefix('B'))
        .unwrap_or(s)
}

/// Direction: `"output"` means the master drives the signal.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PortDir {
    Input,
    Output,
}

/// A single (sub-port name, direction) entry inside an AXI channel.
pub type AxiPortEntry = (&'static str, PortDir);

/// Address-channel ports shared by AR and AW channels.
///
/// This is the *emitted* vocabulary — the sub-ports TAPA's generated
/// fabric declares and wires. `REGION` is deliberately absent: HLS
/// children never produce it, so an emitted `REGION` port would be an
/// undriven top-level output (see
/// [`M_AXI_RECOGNITION_ONLY_SUFFIXES`]).
pub const M_AXI_ADDR_PORTS: &[AxiPortEntry] = &[
    ("ADDR", PortDir::Output),
    ("BURST", PortDir::Output),
    ("CACHE", PortDir::Output),
    ("ID", PortDir::Output),
    ("LEN", PortDir::Output),
    ("LOCK", PortDir::Output),
    ("PROT", PortDir::Output),
    ("QOS", PortDir::Output),
    ("READY", PortDir::Input),
    ("SIZE", PortDir::Output),
    ("VALID", PortDir::Output),
];

/// All five M-AXI channels → their sub-port lists.
pub static M_AXI_PORTS: phf::Map<&'static str, &'static [AxiPortEntry]> = phf::phf_map! {
    "AR" => M_AXI_ADDR_PORTS,
    "AW" => M_AXI_ADDR_PORTS,
    "B" => &[
        ("ID", PortDir::Input),
        ("READY", PortDir::Output),
        ("RESP", PortDir::Input),
        ("VALID", PortDir::Input),
    ],
    "R" => &[
        ("DATA", PortDir::Input),
        ("ID", PortDir::Input),
        ("LAST", PortDir::Input),
        ("READY", PortDir::Output),
        ("RESP", PortDir::Input),
        ("VALID", PortDir::Input),
    ],
    "W" => &[
        ("DATA", PortDir::Output),
        ("LAST", PortDir::Output),
        ("READY", PortDir::Input),
        ("STRB", PortDir::Output),
        ("VALID", PortDir::Output),
    ],
};

// ── M-AXI suffixes ──────────────────────────────────────────────────

/// Compact suffix set (29 entries) — no optional address-channel attributes.
pub const M_AXI_SUFFIXES_COMPACT: &[&str] = &[
    "_ARADDR", "_ARBURST", "_ARID", "_ARLEN", "_ARREADY", "_ARSIZE", "_ARVALID", "_AWADDR",
    "_AWBURST", "_AWID", "_AWLEN", "_AWREADY", "_AWSIZE", "_AWVALID", "_BID", "_BREADY", "_BRESP",
    "_BVALID", "_RDATA", "_RID", "_RLAST", "_RREADY", "_RRESP", "_RVALID", "_WDATA", "_WLAST",
    "_WREADY", "_WSTRB", "_WVALID",
];

/// Optional address-channel attributes that packaged RTL may carry but
/// TAPA's generated fabric never emits or wires.
///
/// They belong to the recognition vocabulary ([`M_AXI_SUFFIXES`]) so
/// consumers that *read* port lists (e.g. the `kernel.xml` base
/// projection at pack time) accept them, and to nothing else: HLS
/// children never produce `REGION`, so emitting it would declare an
/// undriven top-level port.
pub const M_AXI_RECOGNITION_ONLY_SUFFIXES: &[&str] = &["_ARREGION", "_AWREGION"];

/// Full suffix set (39 entries) — compact + 10 optional address-channel
/// attributes, including the recognition-only pair.
pub const M_AXI_SUFFIXES: &[&str] = &[
    "_ARADDR",
    "_ARBURST",
    "_ARID",
    "_ARLEN",
    "_ARREADY",
    "_ARSIZE",
    "_ARVALID",
    "_AWADDR",
    "_AWBURST",
    "_AWID",
    "_AWLEN",
    "_AWREADY",
    "_AWSIZE",
    "_AWVALID",
    "_BID",
    "_BREADY",
    "_BRESP",
    "_BVALID",
    "_RDATA",
    "_RID",
    "_RLAST",
    "_RREADY",
    "_RRESP",
    "_RVALID",
    "_WDATA",
    "_WLAST",
    "_WREADY",
    "_WSTRB",
    "_WVALID",
    "_ARLOCK",
    "_ARPROT",
    "_ARQOS",
    "_ARCACHE",
    "_ARREGION",
    "_AWCACHE",
    "_AWLOCK",
    "_AWPROT",
    "_AWQOS",
    "_AWREGION",
];

/// Per-channel suffix groupings with valid/ready markers.
pub struct AxiChannelInfo {
    pub ports: &'static [&'static str],
    pub valid: &'static str,
    pub ready: &'static str,
}

pub static M_AXI_SUFFIXES_BY_CHANNEL: phf::Map<&'static str, AxiChannelInfo> = phf::phf_map! {
    "AR" => AxiChannelInfo {
        ports: &[
            "_ARADDR", "_ARBURST", "_ARID", "_ARLEN", "_ARREADY", "_ARSIZE",
            "_ARVALID", "_ARLOCK", "_ARPROT", "_ARQOS", "_ARCACHE",
        ],
        valid: "_ARVALID",
        ready: "_ARREADY",
    },
    "AW" => AxiChannelInfo {
        ports: &[
            "_AWADDR", "_AWBURST", "_AWID", "_AWLEN", "_AWREADY", "_AWSIZE",
            "_AWVALID", "_AWLOCK", "_AWPROT", "_AWQOS", "_AWCACHE",
        ],
        valid: "_AWVALID",
        ready: "_AWREADY",
    },
    "B" => AxiChannelInfo {
        ports: &["_BID", "_BREADY", "_BRESP", "_BVALID"],
        valid: "_BVALID",
        ready: "_BREADY",
    },
    "R" => AxiChannelInfo {
        ports: &["_RDATA", "_RID", "_RLAST", "_RREADY", "_RRESP", "_RVALID"],
        valid: "_RVALID",
        ready: "_RREADY",
    },
    "W" => AxiChannelInfo {
        ports: &["_WDATA", "_WLAST", "_WREADY", "_WSTRB", "_WVALID"],
        valid: "_WVALID",
        ready: "_WREADY",
    },
};

// ── M-AXI port lookups ─────────────────────────────────────────────

/// Master-side direction of a full M-AXI port suffix.
///
/// Suffixes look like `_ARADDR` or `_RREADY`; [`PortDir::Output`]
/// means the M-AXI master drives the signal. Returns `None` when
/// `suffix` does not name a port of any of the five M-AXI channels.
#[must_use]
pub fn m_axi_port_direction(suffix: &str) -> Option<PortDir> {
    let suffix_without_underscore = suffix.strip_prefix('_')?;
    let channel = M_AXI_CHANNEL_ORDER
        .iter()
        .find(|channel| suffix_without_underscore.starts_with(**channel))?;
    let subport = axi_subport_from_suffix(suffix);
    M_AXI_PORTS[*channel]
        .iter()
        .find_map(|(name, direction)| (*name == subport).then_some(*direction))
}

// ── Tests ───────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;

    /// The stream tables must agree on which suffixes exist.
    #[test]
    fn stream_suffix_tables_cover_the_same_ports() {
        let declared: BTreeSet<&str> = ISTREAM_SUFFIXES
            .iter()
            .chain(OSTREAM_SUFFIXES.iter())
            .copied()
            .collect();
        let with_direction: BTreeSet<&str> = STREAM_PORT_DIRECTION.keys().copied().collect();

        assert_eq!(declared, with_direction, "direction table");
        assert!(
            STREAM_DATA_SUFFIXES.iter().all(|s| declared.contains(s)),
            "data suffixes must be declared stream suffixes"
        );
    }

    /// The compact suffix set is the full set minus the optional
    /// address-channel attributes — not an independently edited list.
    #[test]
    fn m_axi_compact_suffixes_are_a_subset_of_the_full_set() {
        let full: BTreeSet<&str> = M_AXI_SUFFIXES.iter().copied().collect();
        let compact: BTreeSet<&str> = M_AXI_SUFFIXES_COMPACT.iter().copied().collect();
        assert!(
            compact.is_subset(&full),
            "compact has suffixes the full set lacks"
        );

        let optional: BTreeSet<&str> = full.difference(&compact).copied().collect();
        assert!(
            optional.iter().all(|s| s.ends_with("LOCK")
                || s.ends_with("PROT")
                || s.ends_with("QOS")
                || s.ends_with("CACHE")
                || s.ends_with("REGION")),
            "only LOCK/PROT/QOS/CACHE/REGION are optional, got {optional:?}"
        );
    }

    /// The by-channel grouping covers exactly the emitted suffix set —
    /// the full recognition set minus the recognition-only attributes —
    /// and each channel's valid/ready markers are among its own ports.
    #[test]
    fn m_axi_channels_cover_the_emitted_suffix_set() {
        let mut grouped: Vec<&str> = M_AXI_SUFFIXES_BY_CHANNEL
            .values()
            .flat_map(|c| c.ports.iter().copied())
            .collect();
        let total = grouped.len();
        grouped.sort_unstable();
        grouped.dedup();
        assert_eq!(total, grouped.len(), "a suffix appears in two channels");

        let grouped: BTreeSet<&str> = grouped.into_iter().collect();
        let emitted: BTreeSet<&str> = M_AXI_SUFFIXES
            .iter()
            .copied()
            .filter(|s| !M_AXI_RECOGNITION_ONLY_SUFFIXES.contains(s))
            .collect();
        assert_eq!(grouped, emitted, "channels do not cover the emitted set");

        for (name, channel) in &M_AXI_SUFFIXES_BY_CHANNEL {
            assert!(
                channel.ports.contains(&channel.valid),
                "{name}: valid marker not among its ports"
            );
            assert!(
                channel.ports.contains(&channel.ready),
                "{name}: ready marker not among its ports"
            );
        }
    }

    /// Every M-AXI sub-port named in a channel has a declared width.
    #[test]
    fn m_axi_channel_ports_all_have_widths() {
        for (channel, ports) in &M_AXI_PORTS {
            for (port, _dir) in *ports {
                assert!(
                    M_AXI_PORT_WIDTHS.contains_key(port),
                    "{channel}{port} has no declared width"
                );
            }
        }
    }

    /// The suffix lookup is table-driven and rejects unknown shapes.
    #[test]
    fn m_axi_suffix_lookups_track_the_channel_tables() {
        // Every emitted suffix resolves; the recognition-only pair is
        // deliberately absent from the direction tables — nothing may
        // emit (and so need to direct) a REGION port.
        for &suffix in M_AXI_SUFFIXES {
            let direction = m_axi_port_direction(suffix);
            if M_AXI_RECOGNITION_ONLY_SUFFIXES.contains(&suffix) {
                assert!(direction.is_none(), "{suffix} must stay emission-free");
            } else {
                assert!(direction.is_some(), "{suffix}");
            }
        }

        // Master-side directions straight from the channel tables.
        assert_eq!(m_axi_port_direction("_ARADDR"), Some(PortDir::Output));
        assert_eq!(m_axi_port_direction("_ARREADY"), Some(PortDir::Input));
        assert_eq!(m_axi_port_direction("_BREADY"), Some(PortDir::Output));
        assert_eq!(m_axi_port_direction("_BVALID"), Some(PortDir::Input));
        assert_eq!(m_axi_port_direction("_RREADY"), Some(PortDir::Output));
        assert_eq!(m_axi_port_direction("_RDATA"), Some(PortDir::Input));
        assert_eq!(m_axi_port_direction("_WREADY"), Some(PortDir::Input));
        assert_eq!(m_axi_port_direction("_WSTRB"), Some(PortDir::Output));

        // Unknown shapes are rejected.
        assert_eq!(m_axi_port_direction("_FOO"), None);
        assert_eq!(m_axi_port_direction("ARADDR"), None);
    }

    /// AR and AW are both address channels and must expose the same ports.
    #[test]
    fn m_axi_address_channels_are_symmetric() {
        assert_eq!(
            M_AXI_PORTS["AR"].len(),
            M_AXI_PORTS["AW"].len(),
            "AR and AW must carry the same address ports"
        );
        for ((ar_port, ar_dir), (aw_port, aw_dir)) in
            M_AXI_PORTS["AR"].iter().zip(M_AXI_PORTS["AW"].iter())
        {
            assert_eq!(ar_port, aw_port, "address port mismatch");
            assert_eq!(ar_dir, aw_dir, "address port direction mismatch");
        }
    }
}
