//! TAPA protocol constants.
//!
//! Single source of truth for handshake, stream, FIFO, and M-AXI naming
//! conventions shared across the TAPA toolchain.

// ── Handshake port names ────────────────────────────────────────────

pub const HANDSHAKE_CLK: &str = "ap_clk";
/// Active-high reset generated by TAPA codegen
/// (`assign ap_rst = ~ap_rst_n`).
pub const HANDSHAKE_RST: &str = "ap_rst";
/// Vitis-HLS-internal inverted reset. TAPA never generates this name;
/// it is recognized and stripped from HLS output.
pub const HLS_RST_INV: &str = "ap_rst_n_inv";
pub const HANDSHAKE_RST_N: &str = "ap_rst_n";
pub const HANDSHAKE_START: &str = "ap_start";
pub const HANDSHAKE_DONE: &str = "ap_done";
pub const HANDSHAKE_IDLE: &str = "ap_idle";
pub const HANDSHAKE_READY: &str = "ap_ready";

// ── HLS-internal artifacts stripped by RTL cleanup ──────────────────

/// Clock-enable register emitted by Vitis HLS for multi-cycle blocks.
pub const HLS_CE_REG: &str = "ap_ce_reg";
/// FSM current-state register.
pub const HLS_FSM_CS: &str = "ap_CS_fsm";
/// FSM next-state register.
pub const HLS_FSM_NS: &str = "ap_NS_fsm";
/// FSM per-state parameter/signal name prefix (`ap_ST_fsm_state<N>`).
pub const HLS_FSM_STATE_PREFIX: &str = "ap_ST_fsm_state";

// ── Stream port suffixes ────────────────────────────────────────────

pub const ISTREAM_SUFFIXES: &[&str] = &["_dout", "_empty_n", "_read"];
pub const OSTREAM_SUFFIXES: &[&str] = &["_din", "_full_n", "_write"];
pub const STREAM_DATA_SUFFIXES: &[&str] = &["_dout", "_din"];

/// Width of a stream's data wire for a given element width; the stream
/// payload is widened by one bit.
pub const fn stream_data_wire_width(elem_width: u32) -> u32 {
    elem_width.saturating_add(1)
}

/// Scalar-stream data/flow port name: `{base}_s{suffix}`.
#[must_use]
pub fn stream_port_name(base: &str, suffix: &str) -> String {
    format!("{base}_s{suffix}")
}

/// Scalar-stream peek port name: `{base}_peek{suffix}`; an empty `suffix`
/// names the ostream peek port.
#[must_use]
pub fn stream_peek_port_name(base: &str, suffix: &str) -> String {
    format!("{base}_peek{suffix}")
}

/// Port-name suffix → wire direction (`"input"` or `"output"`).
pub static STREAM_PORT_DIRECTION: phf::Map<&'static str, &'static str> = phf::phf_map! {
    "_dout" => "input",
    "_empty_n" => "input",
    "_read" => "output",
    "_din" => "output",
    "_full_n" => "input",
    "_write" => "output",
};

// ── FIFO interface ports ────────────────────────────────────────────

pub const FIFO_READ_PORTS: &[&str] = &["if_dout", "if_empty_n", "if_read", "if_read_ce"];
pub const FIFO_WRITE_PORTS: &[&str] = &["if_din", "if_full_n", "if_write", "if_write_ce"];

// ── AXI naming prefixes ─────────────────────────────────────────────

pub const S_AXI_NAME: &str = "s_axi_control";

/// AXI-Lite control port names (without the `s_axi_control_` prefix),
/// as exposed by the HLS-generated top-level control interface.
pub const S_AXI_LITE_CTRL_PORTS: &[&str] = &[
    "AWVALID", "AWREADY", "AWADDR", "WVALID", "WREADY", "WDATA", "WSTRB", "ARVALID", "ARREADY",
    "ARADDR", "RVALID", "RREADY", "RDATA", "RRESP", "BVALID", "BREADY", "BRESP",
];

pub const M_AXI_PREFIX: &str = "m_axi_";

// ── M-AXI default parameters ───────────────────────────────────────

/// Default AXI address width in bits: the `m_axi` address bus width
/// produced by HLS and assumed throughout TAPA's generated fabric.
pub const AXI_ADDR_WIDTH: u32 = 64;

/// Default AXI ID width in bits of a port driven directly by an HLS
/// child; TAPA widens IDs only at crossbars for thread routing.
pub const AXI_ID_WIDTH: u32 = 1;

/// Outstanding-transaction budget baked into the generated AXI
/// crossbar wrapper.
///
/// It parameterises both the per-channel `M<idx>_ISSUE` parameter and
/// the per-slave `S_ACCEPT` acceptance count. 16 mirrors the
/// `S_ACCEPT` default of the vendored `axi_crossbar.v`; TAPA applies
/// the same budget to issue tracking.
pub const M_AXI_MAX_OUTSTANDING: u32 = 16;

/// Resolve a sub-port width from the emitted catalog; unknown names use one bit.
#[must_use]
pub fn axi_subport_width(subport: &str, data_width: u32, addr_width: u32, id_width: u32) -> u32 {
    m_axi_ports()
        .find(|port| port.name == subport)
        .map_or(1, |port| port.width(data_width, addr_width, id_width))
}

/// Extract the sub-port name from an M-AXI signal suffix:
/// `_ARADDR` → `ADDR`, `_RDATA` → `DATA`, `_BRESP` → `RESP`.
/// Unknown suffixes are returned with channel prefixes and leading
/// underscores stripped.
#[must_use]
pub fn axi_subport_from_suffix(suffix: &str) -> &str {
    let s = suffix.trim_start_matches('_');
    s.strip_prefix("AR")
        .or_else(|| s.strip_prefix("AW"))
        .or_else(|| s.strip_prefix('R'))
        .or_else(|| s.strip_prefix('W'))
        .or_else(|| s.strip_prefix('B'))
        .unwrap_or(s)
}

/// Direction: `"output"` means the master drives the signal.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PortDir {
    Input,
    Output,
}

/// Width rule stored with each emitted port.
#[derive(Debug, Clone, Copy)]
enum AxiWidth {
    Fixed(u32),
    Address,
    Data,
    Id,
    Strobe,
}

/// An emitted M-AXI port, including its width and compact-fabric membership.
#[derive(Debug, Clone, Copy)]
pub struct AxiPort {
    pub name: &'static str,
    pub suffix: &'static str,
    pub direction: PortDir,
    pub is_compact: bool,
    width: AxiWidth,
}

impl AxiPort {
    /// Resolve parameterized widths; STRB uses `ceil(data_width / 8)`.
    #[must_use]
    pub const fn width(&self, data_width: u32, addr_width: u32, id_width: u32) -> u32 {
        match self.width {
            AxiWidth::Fixed(width) => width,
            AxiWidth::Address => addr_width,
            AxiWidth::Data => data_width,
            AxiWidth::Id => id_width,
            AxiWidth::Strobe => data_width.div_ceil(8),
        }
    }
}

/// An AXI channel in emission order, with its valid/ready markers.
pub struct AxiChannelInfo {
    pub name: &'static str,
    pub ports: &'static [AxiPort],
    pub valid: &'static str,
    pub ready: &'static str,
}

impl AxiChannelInfo {
    pub fn compact_suffixes(&self) -> impl Iterator<Item = &'static str> + '_ {
        self.ports
            .iter()
            .filter(|port| port.is_compact)
            .map(|port| port.suffix)
    }
}

macro_rules! channel {
    ($channel:literal, $(($name:ident, $direction:ident, $width:expr, $compact:literal)),+ $(,)?) => {
        AxiChannelInfo {
            name: $channel,
            valid: concat!("_", $channel, "VALID"),
            ready: concat!("_", $channel, "READY"),
            ports: &[$(AxiPort {
                name: stringify!($name),
                suffix: concat!("_", $channel, stringify!($name)),
                direction: PortDir::$direction,
                width: $width,
                is_compact: $compact,
            }),+],
        }
    };
}

macro_rules! address_channel {
    ($channel:literal) => {
        channel!(
            $channel,
            (ADDR, Output, AxiWidth::Address, true),
            (BURST, Output, AxiWidth::Fixed(2), true),
            (CACHE, Output, AxiWidth::Fixed(4), false),
            (ID, Output, AxiWidth::Id, true),
            (LEN, Output, AxiWidth::Fixed(8), true),
            (LOCK, Output, AxiWidth::Fixed(1), false),
            (PROT, Output, AxiWidth::Fixed(3), false),
            (QOS, Output, AxiWidth::Fixed(4), false),
            (READY, Input, AxiWidth::Fixed(1), true),
            (SIZE, Output, AxiWidth::Fixed(3), true),
            (VALID, Output, AxiWidth::Fixed(1), true),
        )
    };
}

/// Single emitted vocabulary, in canonical channel and sub-port order.
/// REGION is deliberately absent: HLS children never drive it.
pub const M_AXI_CHANNELS: &[AxiChannelInfo] = &[
    address_channel!("AR"),
    address_channel!("AW"),
    channel!(
        "B",
        (ID, Input, AxiWidth::Id, true),
        (READY, Output, AxiWidth::Fixed(1), true),
        (RESP, Input, AxiWidth::Fixed(2), true),
        (VALID, Input, AxiWidth::Fixed(1), true),
    ),
    channel!(
        "R",
        (DATA, Input, AxiWidth::Data, true),
        (ID, Input, AxiWidth::Id, true),
        (LAST, Input, AxiWidth::Fixed(1), true),
        (READY, Output, AxiWidth::Fixed(1), true),
        (RESP, Input, AxiWidth::Fixed(2), true),
        (VALID, Input, AxiWidth::Fixed(1), true),
    ),
    channel!(
        "W",
        (DATA, Output, AxiWidth::Data, true),
        (LAST, Output, AxiWidth::Fixed(1), true),
        (READY, Input, AxiWidth::Fixed(1), true),
        (STRB, Output, AxiWidth::Strobe, true),
        (VALID, Output, AxiWidth::Fixed(1), true),
    ),
];

/// Optional attributes accepted by packaging but never emitted or wired.
pub const M_AXI_RECOGNITION_ONLY_SUFFIXES: &[&str] = &["_ARREGION", "_AWREGION"];

#[must_use]
pub fn m_axi_channel(name: &str) -> Option<&'static AxiChannelInfo> {
    M_AXI_CHANNELS.iter().find(|channel| channel.name == name)
}

pub fn m_axi_ports() -> impl Iterator<Item = &'static AxiPort> {
    M_AXI_CHANNELS.iter().flat_map(|channel| channel.ports)
}

/// Compact fabric ports in emission order, excluding optional attributes.
pub fn m_axi_compact_suffixes() -> impl Iterator<Item = &'static str> {
    M_AXI_CHANNELS
        .iter()
        .flat_map(AxiChannelInfo::compact_suffixes)
}

/// Full recognition vocabulary, including attributes the fabric never emits.
pub fn m_axi_suffixes() -> impl Iterator<Item = &'static str> {
    m_axi_ports()
        .map(|port| port.suffix)
        .chain(M_AXI_RECOGNITION_ONLY_SUFFIXES.iter().copied())
}

/// Master-side direction of an emitted suffix; unknown and recognition-only
/// suffixes have no direction because the fabric must not emit them.
#[must_use]
pub fn m_axi_port_direction(suffix: &str) -> Option<PortDir> {
    m_axi_ports()
        .find(|port| port.suffix == suffix)
        .map(|port| port.direction)
}

// ── Tests ───────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;

    /// The stream tables must agree on which suffixes exist.
    #[test]
    fn stream_suffix_tables_cover_the_same_ports() {
        let declared: BTreeSet<&str> = ISTREAM_SUFFIXES
            .iter()
            .chain(OSTREAM_SUFFIXES.iter())
            .copied()
            .collect();
        let with_direction: BTreeSet<&str> = STREAM_PORT_DIRECTION.keys().copied().collect();

        assert_eq!(declared, with_direction, "direction table");
        assert!(
            STREAM_DATA_SUFFIXES.iter().all(|s| declared.contains(s)),
            "data suffixes must be declared stream suffixes"
        );
    }

    /// The suffix lookup is table-driven and rejects unknown shapes.
    #[test]
    fn m_axi_suffix_lookups_track_the_channel_tables() {
        // Every emitted suffix resolves; the recognition-only pair is
        // deliberately absent from the direction tables — nothing may
        // emit (and so need to direct) a REGION port.
        for suffix in m_axi_suffixes() {
            let direction = m_axi_port_direction(suffix);
            if M_AXI_RECOGNITION_ONLY_SUFFIXES.contains(&suffix) {
                assert!(direction.is_none(), "{suffix} must stay emission-free");
            } else {
                assert!(direction.is_some(), "{suffix}");
            }
        }

        // Master-side directions straight from the channel tables.
        assert_eq!(m_axi_port_direction("_ARADDR"), Some(PortDir::Output));
        assert_eq!(m_axi_port_direction("_ARREADY"), Some(PortDir::Input));
        assert_eq!(m_axi_port_direction("_BREADY"), Some(PortDir::Output));
        assert_eq!(m_axi_port_direction("_BVALID"), Some(PortDir::Input));
        assert_eq!(m_axi_port_direction("_RREADY"), Some(PortDir::Output));
        assert_eq!(m_axi_port_direction("_RDATA"), Some(PortDir::Input));
        assert_eq!(m_axi_port_direction("_WREADY"), Some(PortDir::Input));
        assert_eq!(m_axi_port_direction("_WSTRB"), Some(PortDir::Output));

        // Unknown shapes are rejected.
        assert_eq!(m_axi_port_direction("_FOO"), None);
        assert_eq!(m_axi_port_direction("ARADDR"), None);
    }
}
