"""Cross-language parity tests: Python reference vs Rust `tapa_core`.

These tests drive both the Python TAPA pipeline and the Rust reimplementation
on a single shared fixture, then compare normalized outputs structurally.

The fixture is ``tapa/graphir_conversion/top_conversion_test_files`` — the
same one used by ``project_assembly_test.py`` in the Python tree. It provides
a VecAdd program with slot-task RTL, an FSM, a control_s_axi module, and
cross-references against ``tests/functional/graphir`` for the device config
and floorplan.

Run locally with ``python3 -m pytest tapa-core/tests/parity_test.py``.
"""

# ruff: noqa: PLC0415, E501, ANN401, PT018

from __future__ import annotations

import importlib
import json
import os
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Any

import pytest

# Mirror the loader in python_smoke_test.py so the compiled Rust extension
# is importable when pytest is invoked from the repo root.
for _candidate in ["tapa-core/target/debug", "target/debug"]:
    if os.path.isdir(_candidate):
        sys.path.insert(0, _candidate)
        break

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if _REPO_ROOT.is_dir() and str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

_FIXTURE_DIR = _REPO_ROOT / "tapa" / "graphir_conversion" / "top_conversion_test_files"
_DEVICE_CONFIG = (
    _REPO_ROOT / "tests" / "functional" / "graphir" / "u55c_device_config.json"
)
_FLOORPLAN = _REPO_ROOT / "tests" / "functional" / "graphir" / "floorplan" / "vadd.json"
_TARGET = "xilinx-vitis"
_SLOT_TO_REGION = {
    "SLOT_X0Y2_SLOT_X0Y2": "SLOT_X0Y0:SLOT_X0Y0",
    "SLOT_X2Y3_SLOT_X2Y3": "SLOT_X0Y1:SLOT_X0Y1",
    "SLOT_X3Y3_SLOT_X3Y3": "SLOT_X0Y1:SLOT_X0Y1",
}


def _require_fixture() -> None:
    pytest.importorskip("intervaltree")
    missing = [p for p in (_FIXTURE_DIR, _DEVICE_CONFIG, _FLOORPLAN) if not p.exists()]
    if missing:
        pytest.skip(f"fixture missing: {missing}")


def _copy_rtl_to(dest: Path) -> None:
    dest.mkdir(parents=True, exist_ok=True)
    for rtl in _FIXTURE_DIR.glob("*.v"):
        shutil.copy2(rtl, dest / rtl.name)


def _rtl_sources() -> dict[str, str]:
    """Return ``{task_name: verilog_source}`` for each leaf/upper RTL file.

    Slot task RTL is excluded — those get generated by the lowering pipeline,
    not fed in from module_files.
    """
    out: dict[str, str] = {}
    for rtl in _FIXTURE_DIR.glob("*.v"):
        stem = rtl.stem
        # Skip FSM and control_s_axi RTL; the lowering pipeline reads those
        # from rtl_dir separately.
        if stem.endswith(("_fsm", "_control_s_axi")):
            continue
        out[stem] = rtl.read_text(encoding="utf-8")
    return out


def _build_python_project() -> dict[str, Any]:
    """Run Python's full project-assembly pipeline on the shared fixture.

    Returns the serialized project as a plain Python dict (pydantic model_dump).
    """
    sys.path.insert(0, str(_REPO_ROOT))
    pa_test = importlib.import_module("tapa.graphir_conversion.project_assembly_test")
    gen_rs = importlib.import_module("tapa.graphir_conversion.gen_rs_graphir")

    program = pa_test._build_program()  # type: ignore[attr-defined]  # noqa: SLF001
    project = gen_rs.get_project_from_floorplanned_program(
        program=program,
        device_config=_DEVICE_CONFIG,
        floorplan_path=_FLOORPLAN,
    )
    project.sort_ifaces()
    return project.model_dump(mode="json")


def _build_rust_project(tmpdir: Path) -> dict[str, Any]:
    """Run Rust's ``get_project_from_paths`` on the same fixture."""
    from tapa_core import lowering  # type: ignore[import-not-found]

    rtl_dir = tmpdir / "hdl"
    _copy_rtl_to(rtl_dir)

    with open(_FIXTURE_DIR / "graph.json", encoding="utf-8") as f:
        graph = json.load(f)
    graph["target"] = _TARGET
    graph["slot_task_name_to_fp_region"] = _SLOT_TO_REGION
    design_json = json.dumps(graph)
    modules_json = json.dumps(_rtl_sources())

    project_json = lowering.get_project_from_paths(
        design_json,
        modules_json,
        str(_DEVICE_CONFIG),
        str(_FLOORPLAN),
        str(rtl_dir),
    )
    return json.loads(project_json)


def _extract_ifaces(project: dict[str, Any]) -> dict[str, list[dict[str, Any]]]:
    raw = project.get("ifaces") or {}
    if isinstance(raw, dict):
        return {k: list(v) for k, v in raw.items()}
    return {}


def _extract_module_names(project: dict[str, Any]) -> set[str]:
    return {m["name"] for m in project["modules"]["module_definitions"]}


def _module_port_names(project: dict[str, Any], name: str) -> set[str]:
    for m in project["modules"]["module_definitions"]:
        if m["name"] == name:
            return {p["name"] for p in m.get("ports", [])}
    return set()


def test_parity_module_set() -> None:
    """Python and Rust produce the full, identical module-name set."""
    _require_fixture()
    py_project = _build_python_project()
    with tempfile.TemporaryDirectory() as tmp:
        rust_project = _build_rust_project(Path(tmp))

    py_names = _extract_module_names(py_project)
    rust_names = _extract_module_names(rust_project)
    assert py_names == rust_names, (
        f"module-name mismatch:\n  python-only: {sorted(py_names - rust_names)}\n"
        f"  rust-only:   {sorted(rust_names - py_names)}"
    )


def test_parity_pblocks() -> None:
    """Island pblock map matches between pipelines.

    The Python reference doesn't populate `part_num` at this pipeline stage;
    Rust reads it from `device_config.json`. That's a Python-side gap, not
    a pipeline disagreement, so we only compare the pblock map here.
    """
    _require_fixture()
    py_project = _build_python_project()
    with tempfile.TemporaryDirectory() as tmp:
        rust_project = _build_rust_project(Path(tmp))

    py_pblocks = py_project.get("island_to_pblock_range") or {}
    rust_pblocks = rust_project.get("island_to_pblock_range") or {}
    assert set(py_pblocks.keys()) == set(rust_pblocks.keys()), (
        f"pblock keys differ:\n  python: {sorted(py_pblocks.keys())}\n"
        f"  rust:   {sorted(rust_pblocks.keys())}"
    )
    for key in py_pblocks:
        assert py_pblocks[key] == rust_pblocks[key], (
            f"pblock[{key!r}]:\n  python: {py_pblocks[key]}\n  rust:   {rust_pblocks[key]}"
        )


def test_parity_interface_type_counts() -> None:
    """Same iface-type roster per module across pipelines.

    Covers every module that appears in BOTH iface maps. Modules with
    known fixture-driven divergences (slot stream/mmap port naming) are
    documented inline at the comparison point so a future regression
    surfaces here rather than hiding.
    """
    _require_fixture()
    py_project = _build_python_project()
    with tempfile.TemporaryDirectory() as tmp:
        rust_project = _build_rust_project(Path(tmp))

    py_ifaces = _extract_ifaces(py_project)
    rust_ifaces = _extract_ifaces(rust_project)

    # Iface-key set must match.
    assert set(py_ifaces.keys()) == set(rust_ifaces.keys()), (
        f"iface-key set differs:\n  python: {sorted(py_ifaces.keys())}\n"
        f"  rust:   {sorted(rust_ifaces.keys())}"
    )

    mismatches: list[str] = []
    for module in sorted(set(py_ifaces) & set(rust_ifaces)):
        py_types = sorted(i.get("type", "") for i in py_ifaces.get(module, []))
        rust_types = sorted(i.get("type", "") for i in rust_ifaces.get(module, []))
        if py_types == rust_types:
            continue
        mismatches.append(
            f"interface type roster for {module} differs:\n"
            f"  python: {py_types}\n  rust:   {rust_types}"
        )

    assert not mismatches, "iface roster mismatch:\n" + "\n".join(mismatches)


def test_parity_ctrl_s_axi_ports() -> None:
    """The emitted control_s_axi module has the same ports on both sides."""
    _require_fixture()
    py_project = _build_python_project()
    with tempfile.TemporaryDirectory() as tmp:
        rust_project = _build_rust_project(Path(tmp))

    py_ports = _module_port_names(py_project, "VecAdd_control_s_axi")
    rust_ports = _module_port_names(rust_project, "VecAdd_control_s_axi")
    # Core AXI-Lite ports both sides must agree on.
    core_ports = {
        "ACLK",
        "ARESET",
        "AWVALID",
        "AWREADY",
        "AWADDR",
        "WVALID",
        "WREADY",
        "WDATA",
        "WSTRB",
        "ARVALID",
        "ARREADY",
        "ARADDR",
        "RVALID",
        "RREADY",
        "RDATA",
        "RRESP",
        "BVALID",
        "BREADY",
        "BRESP",
        "ap_start",
        "ap_done",
        "ap_ready",
        "ap_idle",
        "interrupt",
    }
    assert core_ports.issubset(py_ports), (
        f"Python ctrl_s_axi missing core ports: {core_ports - py_ports}"
    )
    assert core_ports.issubset(rust_ports), (
        f"Rust ctrl_s_axi missing core ports: {core_ports - rust_ports}"
    )


def _build_python_abgraph() -> dict[str, Any]:
    """Run Python's ABGraph generator on the shared VecAdd program + fp config.

    The shared fixture doesn't populate synthesis area per task, so we
    stamp a placeholder zero-area onto every task before running. Rust's
    `collect_task_area` does the same thing internally (defaults to zero
    when `annotations.total_area` is absent), so both sides start from
    the same zero baseline for area comparison.
    """
    sys.path.insert(0, str(_REPO_ROOT))
    pa_test = importlib.import_module("tapa.graphir_conversion.project_assembly_test")
    gen_abgraph = importlib.import_module("tapa.abgraph.gen_abgraph")

    program = pa_test._build_program()  # type: ignore[attr-defined]  # noqa: SLF001
    zero_area = {"LUT": 0, "FF": 0, "BRAM_18K": 0, "DSP": 0, "URAM": 0}
    for task in program._tasks.values():  # noqa: SLF001
        # The property setter refuses to overwrite; assign the backing
        # field directly so both leaf and upper tasks get a stamp.
        task._self_area = dict(zero_area)  # noqa: SLF001
        task._total_area = dict(zero_area)  # noqa: SLF001

    fp_config = _REPO_ROOT / "tests" / "functional" / "abgraph" / "test_fp_config.json"
    graph = gen_abgraph.get_top_level_ab_graph(program, fp_config)
    return graph.model_dump(mode="json")


def _build_rust_abgraph() -> dict[str, Any]:
    """Run Rust's ABGraph generator (RTL-aware) on the same fixture."""
    from tapa_core import floorplan  # type: ignore[import-not-found]

    with open(_FIXTURE_DIR / "graph.json", encoding="utf-8") as f:
        graph = json.load(f)
    graph["target"] = _TARGET
    graph["slot_task_name_to_fp_region"] = _SLOT_TO_REGION
    design_json = json.dumps(graph)
    modules_json = json.dumps(_rtl_sources())

    # Use the RTL-aware entrypoint so FIFO widths and port widths are
    # derived from the actual Verilog (matching what Python does via the
    # program's attached modules).
    result = floorplan.get_top_level_ab_graph_from_rtl(
        design_json, modules_json, "{}", "VecAdd_fsm"
    )
    return json.loads(result)


def test_parity_abgraph_vertex_set() -> None:
    """Python and Rust produce identical ABGraph vertex sets (names)."""
    _require_fixture()
    py_ab = _build_python_abgraph()
    rust_ab = _build_rust_abgraph()

    py_names = {v["name"] for v in py_ab.get("vs") or []}
    rust_names = {v["name"] for v in rust_ab.get("vs") or []}
    assert py_names == rust_names, (
        f"ABGraph vertex-name mismatch:\n"
        f"  python-only: {sorted(py_names - rust_names)}\n"
        f"  rust-only:   {sorted(rust_names - py_names)}"
    )


def _vertex_name(entry: Any) -> str:
    """Return the vertex name regardless of serialization shape.

    Python's Pydantic model serializes ``source_vertex``/``target_vertex``
    as nested dicts; Rust serializes them as name strings directly.
    """
    if isinstance(entry, dict):
        return entry.get("name", "")
    if isinstance(entry, str):
        return entry
    return ""


def test_parity_abgraph_edge_connectivity() -> None:
    """The (src, dst, width) edge set matches across pipelines."""
    _require_fixture()
    py_ab = _build_python_abgraph()
    rust_ab = _build_rust_abgraph()

    def edge_triples(ab: dict[str, Any]) -> set[tuple[str, str, int]]:
        # Include width — the legacy bug was that Rust's FIFO-width lookup
        # missed the slot-wrapper `_s_din` infix and fell back to topology
        # width 32 while Python computed 33 from the `[32:0]` RTL signal.
        # Without the width field in the key, that bug sailed past parity.
        return {
            (
                _vertex_name(e.get("source_vertex")),
                _vertex_name(e.get("target_vertex")),
                int(e.get("width") or 0),
            )
            for e in ab.get("es") or []
        }

    py_edges = edge_triples(py_ab)
    rust_edges = edge_triples(rust_ab)
    assert py_edges == rust_edges, (
        f"ABGraph edge (src,dst,width) mismatch:\n"
        f"  python-only: {sorted(py_edges - rust_edges)}\n"
        f"  rust-only:   {sorted(rust_edges - py_edges)}"
    )


def test_parity_abgraph_full_normalized() -> None:
    """Normalized JSON-equivalent ABGraph on the shared fixture.

    Normalizes only serialization-shape differences (Python's nested-dict
    vertex references vs Rust's flat-string references, and Python's
    optional-null fields that Rust omits) — **not** semantic fields like
    edge `width`. If the two pipelines disagree on any semantic field,
    this test fails.
    """
    _require_fixture()
    py_ab = _build_python_abgraph()
    rust_ab = _build_rust_abgraph()

    # Canonicalize an edge: flatten vertex references to just the name,
    # drop absent/null-only ABVertex bookkeeping that the two sides
    # serialize differently.
    def canonical_edge(e: dict[str, Any]) -> dict[str, Any]:
        return {
            "index": e.get("index"),
            "source": _vertex_name(e.get("source_vertex")),
            "target": _vertex_name(e.get("target_vertex")),
            "width": e.get("width"),
            "depth": e.get("depth"),
        }

    def canonical_vertex(v: dict[str, Any]) -> dict[str, Any]:
        return {
            "name": v.get("name"),
            "area": v.get("area") or {},
            "sub_cells": sorted(v.get("sub_cells") or []),
        }

    py_edges = sorted(
        (canonical_edge(e) for e in py_ab.get("es") or []),
        key=lambda e: (e["source"], e["target"], e.get("index", 0)),
    )
    rust_edges = sorted(
        (canonical_edge(e) for e in rust_ab.get("es") or []),
        key=lambda e: (e["source"], e["target"], e.get("index", 0)),
    )
    assert py_edges == rust_edges, (
        "ABGraph canonical edge list differs — "
        f"python({len(py_edges)}) vs rust({len(rust_edges)})"
    )

    py_vs = sorted(
        (canonical_vertex(v) for v in py_ab.get("vs") or []),
        key=lambda v: v["name"],
    )
    rust_vs = sorted(
        (canonical_vertex(v) for v in rust_ab.get("vs") or []),
        key=lambda v: v["name"],
    )
    assert py_vs == rust_vs, (
        "ABGraph canonical vertex list differs — "
        f"python({len(py_vs)}) vs rust({len(rust_vs)})"
    )


def test_parity_abgraph_vertex_areas() -> None:
    """per-vertex area (lut/ff/bram/dsp/uram) matches across pipelines."""
    _require_fixture()
    py_ab = _build_python_abgraph()
    rust_ab = _build_rust_abgraph()

    def by_name(ab: dict[str, Any]) -> dict[str, dict[str, Any]]:
        return {v["name"]: (v.get("area") or {}) for v in ab.get("vs") or []}

    py_areas = by_name(py_ab)
    rust_areas = by_name(rust_ab)
    common = set(py_areas.keys()) & set(rust_areas.keys())
    assert common, "expected at least one common vertex across pipelines"
    for name in sorted(common):
        for field in ("lut", "ff", "bram_18k", "dsp", "uram"):
            py_v = py_areas[name].get(field, 0)
            rust_v = rust_areas[name].get(field, 0)
            assert py_v == rust_v, f"area[{name}][{field}]: python={py_v} rust={rust_v}"


def _normalize_port_list(ports: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Canonicalize a port list: drop null fields, sort by name."""
    return sorted(
        ({k: v for k, v in p.items() if v is not None} for p in ports or []),
        key=lambda p: p.get("name", ""),
    )


def _normalize_wire_list(wires: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Canonicalize a wire list: drop null fields, sort by name."""
    return sorted(
        ({k: v for k, v in (w or {}).items() if v is not None} for w in wires or []),
        key=lambda w: w.get("name", ""),
    )


def _normalize_param_list(params: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Canonicalize parameter list: drop nulls, sort by name."""
    return sorted(
        ({k: v for k, v in (p or {}).items() if v is not None} for p in params or []),
        key=lambda p: p.get("name", ""),
    )


def _normalize_submodule(sub: dict[str, Any]) -> dict[str, Any]:
    """Canonicalize a submodule entry: sort connections / parameters by name."""
    return {
        "name": sub.get("name"),
        "module": sub.get("module"),
        "floorplan_region": sub.get("floorplan_region"),
        "connections": sorted(
            (
                {k: v for k, v in c.items() if v is not None}
                for c in (sub.get("connections") or [])
            ),
            key=lambda c: c.get("name", ""),
        ),
        "parameters": sorted(
            (
                {k: v for k, v in p.items() if v is not None}
                for p in (sub.get("parameters") or [])
            ),
            key=lambda p: p.get("name", ""),
        ),
    }


def _normalize_submodule_list(subs: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return sorted(
        (_normalize_submodule(s) for s in subs or []),
        key=lambda s: s.get("name", ""),
    )


def test_parity_full_project_normalized() -> None:
    """Full normalized module equality across every common module.

    For each module the Python and Rust pipelines both emit, this test
    asserts equality of the full normalized object: parameters, ports,
    wires, and submodules (with each submodule's connections and
    parameters). No exemptions — any divergence on any field is a
    failure. Lists are sorted by name for order-independence since the
    GraphIR schema does not mandate emission order.
    """
    _require_fixture()
    py_project = _build_python_project()
    with tempfile.TemporaryDirectory() as tmp:
        rust_project = _build_rust_project(Path(tmp))

    py_names = sorted(_extract_module_names(py_project))
    rust_names = sorted(_extract_module_names(rust_project))
    assert py_names == rust_names, (
        f"module roster mismatch:\n  python: {py_names}\n  rust:   {rust_names}"
    )

    mismatches: list[str] = []
    for name in py_names:
        py_mod = next(
            m for m in py_project["modules"]["module_definitions"] if m["name"] == name
        )
        rust_mod = next(
            m
            for m in rust_project["modules"]["module_definitions"]
            if m["name"] == name
        )

        for field, normalize in (
            ("parameters", _normalize_param_list),
            ("ports", _normalize_port_list),
            ("wires", _normalize_wire_list),
            ("submodules", _normalize_submodule_list),
        ):
            py_v = normalize(py_mod.get(field) or [])
            rust_v = normalize(rust_mod.get(field) or [])
            if py_v != rust_v:
                py_names_set: set[str] = {
                    str(e.get("name", "")) for e in py_v if isinstance(e, dict)
                }
                rust_names_set: set[str] = {
                    str(e.get("name", "")) for e in rust_v if isinstance(e, dict)
                }
                only_py = sorted(py_names_set - rust_names_set)
                only_rust = sorted(rust_names_set - py_names_set)
                mismatches.append(
                    f"{name}.{field}: py={len(py_v)} rust={len(rust_v)}"
                    f" py_only={only_py[:8]} rust_only={only_rust[:8]}"
                )

    assert not mismatches, "full-project equality failed:\n" + "\n".join(mismatches)


def _find_param(module: dict[str, Any], pname: str) -> dict[str, Any] | None:
    for p in module.get("parameters") or []:
        if p.get("name") == pname:
            return p
    return None


def _find_port(module: dict[str, Any], pname: str) -> dict[str, Any] | None:
    for p in module.get("ports") or []:
        if p.get("name") == pname:
            return p
    return None


def _find_submodule(module: dict[str, Any], sname: str) -> dict[str, Any] | None:
    for s in module.get("submodules") or []:
        if s.get("name") == sname:
            return s
    return None


def test_parity_slot_fsm_state_expressions() -> None:
    """Regression: slot grouped modules emit first-seen FSM-state expressions.

    Python's ``get_slot_module_definition_parameters`` walks leaf IRs in
    instance order and keeps the first-seen `ModuleParameter` for each
    name. The first leaf (`Mmap2Stream`) declares 10-bit FSM states
    (`10'd*`), so every slot inherits that expression. Rust iterating
    `state.module_map` alphabetically would instead pick up
    `Add`'s 3-bit expression (`3'd*`) — this test guards against that
    regression on all three slot modules.
    """
    _require_fixture()
    py_project = _build_python_project()
    with tempfile.TemporaryDirectory() as tmp:
        rust_project = _build_rust_project(Path(tmp))

    slot_names = [
        "SLOT_X0Y2_SLOT_X0Y2",
        "SLOT_X2Y3_SLOT_X2Y3",
        "SLOT_X3Y3_SLOT_X3Y3",
    ]
    for slot in slot_names:
        py_mod = next(
            (
                m
                for m in py_project["modules"]["module_definitions"]
                if m["name"] == slot
            ),
            None,
        )
        rust_mod = next(
            (
                m
                for m in rust_project["modules"]["module_definitions"]
                if m["name"] == slot
            ),
            None,
        )
        assert py_mod is not None, f"python missing slot {slot}"
        assert rust_mod is not None, f"rust missing slot {slot}"

        for pname in ("ap_ST_fsm_state1", "ap_ST_fsm_state2", "ap_ST_fsm_state3"):
            py_param = _find_param(py_mod, pname)
            rust_param = _find_param(rust_mod, pname)
            if py_param is None:
                # If Python doesn't emit it either, skip.
                continue
            assert rust_param is not None, (
                f"{slot}.{pname}: missing from Rust (Python has {py_param['expr']})"
            )
            assert py_param["expr"] == rust_param["expr"], (
                f"{slot}.{pname}: py={py_param['expr']} rust={rust_param['expr']}"
            )


def test_parity_fifo_submodule_objects() -> None:
    """Regression: FIFO submodule parameters and reset wiring match.

    Directly asserts VecAdd.a_q_VecAdd / c_q_VecAdd (top FIFOs) and
    SLOT_X3Y3_SLOT_X3Y3.b_q_VecAdd (slot-local FIFO) carry the exact
    Python DATA_WIDTH (`33`) and reset expression (`rst` on top,
    `~ap_rst_n` on slot). Guards against regressions that would wire
    FIFO resets to `ap_rst` or leave DATA_WIDTH at the topology-derived
    32.
    """
    _require_fixture()
    py_project = _build_python_project()
    with tempfile.TemporaryDirectory() as tmp:
        rust_project = _build_rust_project(Path(tmp))

    def _find_mod(project: dict[str, Any], name: str) -> dict[str, Any]:
        for m in project["modules"]["module_definitions"]:
            if m["name"] == name:
                return m
        msg = f"missing module {name}"
        raise AssertionError(msg)

    for parent, sub_name in [
        ("VecAdd", "a_q_VecAdd"),
        ("VecAdd", "c_q_VecAdd"),
        ("SLOT_X3Y3_SLOT_X3Y3", "b_q_VecAdd"),
    ]:
        py_mod = _find_mod(py_project, parent)
        rust_mod = _find_mod(rust_project, parent)
        py_sub = _find_submodule(py_mod, sub_name)
        rust_sub = _find_submodule(rust_mod, sub_name)
        assert py_sub is not None, f"python missing {parent}.{sub_name}"
        assert rust_sub is not None, f"rust missing {parent}.{sub_name}"

        py_dw = next(p for p in py_sub["parameters"] if p["name"] == "DATA_WIDTH")
        rust_dw = next(p for p in rust_sub["parameters"] if p["name"] == "DATA_WIDTH")
        assert py_dw["expr"] == rust_dw["expr"], (
            f"{parent}.{sub_name}.DATA_WIDTH: py={py_dw['expr']} rust={rust_dw['expr']}"
        )

        py_reset = next(c for c in py_sub["connections"] if c["name"] == "reset")
        rust_reset = next(c for c in rust_sub["connections"] if c["name"] == "reset")
        assert py_reset["expr"] == rust_reset["expr"], (
            f"{parent}.{sub_name}.reset: py={py_reset['expr']} rust={rust_reset['expr']}"
        )


def test_parity_ctrl_s_axi_inst_parameters_and_wstrb() -> None:  # noqa: PLR0914
    """Regression: ``control_s_axi_U`` params + ``WSTRB`` tokenization match Python.

    ``control_s_axi_U.parameters`` copies the top task's literal
    parameter expressions (``6`` / ``32``). ``WSTRB`` port range
    tokenizes to the 5-token stream Python emits.
    """
    _require_fixture()
    py_project = _build_python_project()
    with tempfile.TemporaryDirectory() as tmp:
        rust_project = _build_rust_project(Path(tmp))

    def _find_mod(project: dict[str, Any], name: str) -> dict[str, Any]:
        for m in project["modules"]["module_definitions"]:
            if m["name"] == name:
                return m
        msg = f"missing module {name}"
        raise AssertionError(msg)

    # ``control_s_axi_U`` instance lives inside VecAdd; parameters should
    # copy the literal expressions `6` / `32` from the top's parameters.
    py_top = _find_mod(py_project, "VecAdd")
    rust_top = _find_mod(rust_project, "VecAdd")
    py_ctrl = _find_submodule(py_top, "control_s_axi_U")
    rust_ctrl = _find_submodule(rust_top, "control_s_axi_U")
    assert py_ctrl is not None and rust_ctrl is not None
    py_params = sorted(py_ctrl["parameters"], key=lambda p: p["name"])
    rust_params = sorted(rust_ctrl["parameters"], key=lambda p: p["name"])
    py_normalized = [{k: v for k, v in p.items() if v is not None} for p in py_params]
    rust_normalized = [
        {k: v for k, v in p.items() if v is not None} for p in rust_params
    ]
    assert py_normalized == rust_normalized, (
        f"control_s_axi_U.parameters differ:\n  py: {py_normalized}\n  rs: {rust_normalized}"
    )

    # WSTRB on the ctrl_s_axi module must tokenize as
    # [id(C_S_AXI_DATA_WIDTH), lit(/), lit(8), lit(-), lit(1)].
    py_ctrl_mod = _find_mod(py_project, "VecAdd_control_s_axi")
    rust_ctrl_mod = _find_mod(rust_project, "VecAdd_control_s_axi")
    py_wstrb = _find_port(py_ctrl_mod, "WSTRB")
    rust_wstrb = _find_port(rust_ctrl_mod, "WSTRB")
    assert py_wstrb is not None and rust_wstrb is not None
    py_norm = {k: v for k, v in py_wstrb.items() if v is not None}
    rust_norm = {k: v for k, v in rust_wstrb.items() if v is not None}
    assert py_norm == rust_norm, (
        f"WSTRB port differs:\n  py: {py_norm}\n  rs: {rust_norm}"
    )


def test_parity_upper_module_parameters() -> None:
    """Upper grouped modules carry their Vitis-declared parameters.

    Python's `ports_builder` additionally **aggregates** parameters from the
    child-leaf RTL (e.g., `ap_ST_fsm_state*`) into slot modules. Rust only
    lifts the slot task's own declared RTL parameters into the grouped
    module. The aggregation logic is a deeper tapa-rtl/tapa-lowering
    integration outside this round's scope.

    This test verifies:
      * Every non-empty Python parameter list has a matching Rust entry
        on the top module (VecAdd).
      * Slot modules carry *at least* their own RTL-declared parameters
        (the aggregation delta is tolerated with a documented inline
        comment).
    """
    _require_fixture()
    py_project = _build_python_project()
    with tempfile.TemporaryDirectory() as tmp:
        rust_project = _build_rust_project(Path(tmp))

    def param_names(project: dict[str, Any], name: str) -> set[str]:
        for m in project["modules"]["module_definitions"]:
            if m["name"] == name:
                return {p["name"] for p in m.get("parameters") or []}
        return set()

    # Top task VecAdd: full parameter parity is expected (both sides derive
    # from the top RTL directly; nothing is aggregated in for the top).
    py_top_params = param_names(py_project, "VecAdd")
    rust_top_params = param_names(rust_project, "VecAdd")
    only_py_top = sorted(py_top_params - rust_top_params)
    assert not only_py_top, f"VecAdd parameter mismatch, python-only: {only_py_top}"

    # Slot modules: Rust now mirrors Python's
    # `get_slot_module_definition_parameters`, aggregating every child-leaf
    # RTL parameter into the slot's parameter list. Asserts every Python
    # parameter on each slot appears on the Rust side.
    for slot_name in _SLOT_TO_REGION:
        py_slot_params = param_names(py_project, slot_name)
        rust_slot_params = param_names(rust_project, slot_name)
        assert py_slot_params, (
            f"Python should carry aggregated params on {slot_name}; "
            "aggregation logic may have regressed"
        )
        only_py = sorted(py_slot_params - rust_slot_params)
        assert not only_py, (
            f"{slot_name}: python-only parameters missing from Rust: {only_py}"
        )


def test_parity_top_slot_instances_floorplan_region() -> None:
    """top-module slot instantiations carry physical floorplan regions.

    Rust emits `floorplan_region` on each slot-instance submodule of the
    top module. Python uses `program.slot_task_name_to_fp_region` for this,
    so Rust must do the same. The regions are the physical
    ``SLOT_X0Y0:SLOT_X0Y0`` / ``SLOT_X0Y1:SLOT_X0Y1`` values, not the
    pre-baked slot-task names.
    """
    _require_fixture()
    with tempfile.TemporaryDirectory() as tmp:
        rust_project = _build_rust_project(Path(tmp))

    top_module = next(
        m
        for m in rust_project["modules"]["module_definitions"]
        if m["name"] == "VecAdd"
    )
    slot_insts = [
        inst
        for inst in top_module.get("submodules", [])
        if inst.get("module", "").startswith("SLOT_X")
    ]
    assert slot_insts, "expected top module to have slot instances"
    expected_regions = set(_SLOT_TO_REGION.values())
    actual_regions = {inst.get("floorplan_region") for inst in slot_insts}
    # Every slot instance must carry a physical floorplan region.
    missing = actual_regions - expected_regions
    assert not missing, (
        f"slot instances carry unexpected floorplan_region values:\n"
        f"  actual:  {sorted(r for r in actual_regions if r)}\n"
        f"  expected subset of: {sorted(expected_regions)}"
    )


def test_parity_top_submodules_floorplan_region() -> None:
    """Every top-module submodule carries a physical floorplan region.

    Python's get_top_module_definition passes a `default_region` (the
    first value of slot_task_name_to_fp_region) to the top FSM,
    control_s_axi_U, reset_inverter_0. Slot instances use their own
    region mapping. No top submodule should have `floorplan_region: None`.
    """
    _require_fixture()
    with tempfile.TemporaryDirectory() as tmp:
        rust_project = _build_rust_project(Path(tmp))

    top_module = next(
        m
        for m in rust_project["modules"]["module_definitions"]
        if m["name"] == "VecAdd"
    )
    expected_regions = set(_SLOT_TO_REGION.values())
    missing_region: list[str] = []
    unexpected: list[str] = []
    for inst in top_module.get("submodules", []):
        region = inst.get("floorplan_region")
        if region is None:
            missing_region.append(inst.get("name", "?"))
            continue
        if region not in expected_regions:
            unexpected.append(f"{inst.get('name')}={region!r}")
    assert not missing_region, (
        f"top submodules missing floorplan_region: {missing_region}"
    )
    assert not unexpected, (
        f"top submodules with unexpected region: {unexpected}; "
        f"expected one of {sorted(expected_regions)}"
    )


def test_parity_ctrl_s_axi_inst_has_parameters() -> None:
    """control_s_axi_U carries the Vitis C_S_AXI parameter assignments.

    Python's get_top_ctrl_s_axi_inst passes C_S_AXI_ADDR_WIDTH and
    C_S_AXI_DATA_WIDTH as parameter connections on the ctrl_s_axi_U
    instantiation; Rust must do the same.
    """
    _require_fixture()
    with tempfile.TemporaryDirectory() as tmp:
        rust_project = _build_rust_project(Path(tmp))
    top_module = next(
        m
        for m in rust_project["modules"]["module_definitions"]
        if m["name"] == "VecAdd"
    )
    ctrl_inst = next(
        (
            inst
            for inst in top_module.get("submodules", [])
            if inst.get("name") == "control_s_axi_U"
        ),
        None,
    )
    assert ctrl_inst is not None, "expected control_s_axi_U in top submodules"
    param_names = {p.get("name") for p in ctrl_inst.get("parameters") or []}
    assert "C_S_AXI_ADDR_WIDTH" in param_names, param_names
    assert "C_S_AXI_DATA_WIDTH" in param_names, param_names


def test_parity_slot_fsm_submodule_present() -> None:
    """Every slot module contains a self-connected slot FSM instance.

    Matches Python's ``get_upper_module_ir_subinsts`` which appends
    ``_make_fsm_inst(upper_task.rtl_fsm_module, floorplan_region)``. Rust
    must emit an FSM submodule for every slot in the shared fixture.
    """
    _require_fixture()
    with tempfile.TemporaryDirectory() as tmp:
        rust_project = _build_rust_project(Path(tmp))
    for slot_name in _SLOT_TO_REGION:
        slot_module = next(
            m
            for m in rust_project["modules"]["module_definitions"]
            if m["name"] == slot_name
        )
        fsm_subs = [
            inst
            for inst in slot_module.get("submodules", [])
            if inst.get("module") == f"{slot_name}_fsm"
        ]
        assert len(fsm_subs) == 1, (
            f"{slot_name} should have exactly one slot-FSM submodule, "
            f"got {len(fsm_subs)}"
        )
        assert fsm_subs[0]["name"] == f"{slot_name}_fsm_0", fsm_subs[0]["name"]


def test_parity_slot_local_fifo_submodule_present() -> None:
    """slot-local FIFOs (intra-slot) appear as `fifo` submodules.

    Each slot task in graph.json has its own ``fifos`` map. Entries with
    both ``produced_by`` and ``consumed_by`` set are intra-slot FIFOs that
    Python's ``get_upper_module_ir_subinsts`` instantiates as ``fifo``
    submodules on the slot grouped module. Rust must do the same —
    walking the slot task's own fifos, not `top.fifos`.

    On the shared VecAdd fixture, ``SLOT_X3Y3_SLOT_X3Y3`` has
    ``b_q_VecAdd`` as a depth-2 local FIFO (Mmap2Stream_0 → Add_0).
    """
    _require_fixture()
    with tempfile.TemporaryDirectory() as tmp:
        rust_project = _build_rust_project(Path(tmp))
    slot_module = next(
        m
        for m in rust_project["modules"]["module_definitions"]
        if m["name"] == "SLOT_X3Y3_SLOT_X3Y3"
    )
    fifo_subs = {
        inst["name"]
        for inst in slot_module.get("submodules", [])
        if inst.get("module") == "fifo"
    }
    assert "b_q_VecAdd" in fifo_subs, (
        f"SLOT_X3Y3_SLOT_X3Y3 should instantiate the local FIFO "
        f"`b_q_VecAdd`; got fifo submodules: {sorted(fifo_subs)}"
    )


def test_parity_top_fifo_submodules_present() -> None:
    """cross-slot top FIFOs appear as ``fifo`` submodules on the top.

    Matches Python's ``get_top_ir_subinsts`` which appends a ``fifo``
    instance for every cross-slot FIFO in ``top.fifos``. On the shared
    VecAdd fixture those are ``a_q_VecAdd``, ``b_q_VecAdd``, ``c_q_VecAdd``.
    """
    _require_fixture()
    with tempfile.TemporaryDirectory() as tmp:
        rust_project = _build_rust_project(Path(tmp))
    top_module = next(
        m
        for m in rust_project["modules"]["module_definitions"]
        if m["name"] == "VecAdd"
    )
    fifo_inst_names = {
        inst["name"]
        for inst in top_module.get("submodules", [])
        if inst.get("module") == "fifo"
    }
    # VecAdd.fifos in the shared graph.json has a_q_VecAdd and c_q_VecAdd
    # (cross-slot FIFOs); both Python and Rust must emit them.
    expected = {"a_q_VecAdd", "c_q_VecAdd"}
    assert expected.issubset(fifo_inst_names), (
        f"top FIFOs missing from Rust: {expected - fifo_inst_names}"
    )


def test_parity_reset_inverter_connects_to_rst_wire() -> None:
    """``reset_inverter_0.rst`` connects to the `rst` wire, not `ap_rst`.

    Matches Python's ``get_reset_inverter_inst`` port mapping.
    """
    _require_fixture()
    with tempfile.TemporaryDirectory() as tmp:
        rust_project = _build_rust_project(Path(tmp))
    top_module = next(
        m
        for m in rust_project["modules"]["module_definitions"]
        if m["name"] == "VecAdd"
    )
    reset_inst = next(
        (
            inst
            for inst in top_module.get("submodules", [])
            if inst.get("name") == "reset_inverter_0"
        ),
        None,
    )
    assert reset_inst is not None, "expected reset_inverter_0 in top submodules"
    rst_conn = next(
        (c for c in reset_inst.get("connections") or [] if c.get("name") == "rst"),
        None,
    )
    assert rst_conn is not None, "reset_inverter_0 missing `rst` connection"
    expr = rst_conn.get("expr") or []
    if isinstance(expr, list):
        rst_target = "".join(tok.get("repr", "") for tok in expr)
    else:
        rst_target = str(expr)
    assert "rst" in rst_target and "ap_rst" not in rst_target, (
        f"reset_inverter_0.rst should connect to `rst` wire, got {rst_target!r}"
    )


def test_parity_top_slot_instance_names() -> None:
    """top-module slot instances follow Python's `{slot}_0` naming."""
    _require_fixture()
    with tempfile.TemporaryDirectory() as tmp:
        rust_project = _build_rust_project(Path(tmp))
    top_module = next(
        m
        for m in rust_project["modules"]["module_definitions"]
        if m["name"] == "VecAdd"
    )
    slot_inst_names = {
        inst["name"]
        for inst in top_module.get("submodules", [])
        if inst.get("module", "").startswith("SLOT_X")
    }
    expected = {f"{slot}_0" for slot in _SLOT_TO_REGION}
    assert slot_inst_names == expected, (
        f"slot instance names: {sorted(slot_inst_names)} != expected {sorted(expected)}"
    )


def _export_python_non_grouped_modules() -> dict[str, str]:
    """Export Python non-grouped modules by name → Verilog text.

    The shared fixture has grouped modules (top / slots) that fail Python
    DRC (missing wires in slot modules). Non-grouped modules (fifo,
    reset_inverter, leaf tasks, FSMs, ctrl_s_axi) export cleanly. This
    helper returns just those so per-module parsed-Verilog parity can be
    compared module-by-module.
    """
    sys.path.insert(0, str(_REPO_ROOT))
    py_verilog = importlib.import_module("tapa.verilog.graphir_exporter.verilog")
    py_project = _build_python_project_obj()
    out: dict[str, str] = {}
    for module in py_project.modules.module_definitions:
        type_name = type(module).__name__
        if type_name == "GroupedModuleDefinition":
            continue
        out[module.name] = py_verilog.export_verilog_design(module)
    return out


def _build_python_project_obj() -> Any:
    """Return the raw Python Project object (for non-grouped module export)."""
    sys.path.insert(0, str(_REPO_ROOT))
    pa_test = importlib.import_module("tapa.graphir_conversion.project_assembly_test")
    gen_rs = importlib.import_module("tapa.graphir_conversion.gen_rs_graphir")
    program = pa_test._build_program()  # type: ignore[attr-defined]  # noqa: SLF001
    return gen_rs.get_project_from_floorplanned_program(
        program=program,
        device_config=_DEVICE_CONFIG,
        floorplan_path=_FLOORPLAN,
    )


def test_parity_parsed_verilog_infrastructure_modules() -> None:
    """Parsed-Verilog parity for every non-grouped module both sides emit.

    For each module that both Python and Rust produce in the lowering pass,
    export the Python Verilog text via the Python exporter and the Rust
    Verilog via Rust's exporter, reparse both with ``tapa_core.rtl.parse``,
    and assert the parsed port-name sets match. Byte-level differences
    (formatting, comments) are tolerated; semantic structure is not.
    """
    _require_fixture()
    from tapa_core import graphir_export, rtl  # type: ignore[import-not-found]

    py_verilog = _export_python_non_grouped_modules()

    with tempfile.TemporaryDirectory() as rust_tmp:
        rust_project = _build_rust_project(Path(rust_tmp))
        # Strip grouped modules so the exporter's DRC pass doesn't flag
        # fixture-side missing wires that Python also fails on. We only
        # compare non-grouped infrastructure modules (fifo, reset_inverter,
        # ctrl_s_axi, FSMs, leaf tasks), not the grouped top/slot RTL.
        infra_only = {
            **rust_project,
            "modules": {
                **rust_project["modules"],
                "module_definitions": [
                    m
                    for m in rust_project["modules"]["module_definitions"]
                    if m.get("module_type") != "grouped_module"
                ],
                "top_name": None,
            },
            "ifaces": None,
        }
        rust_dest = Path(rust_tmp) / "rust_export"
        rust_dest.mkdir()
        graphir_export.export_project(json.dumps(infra_only), str(rust_dest))
        rust_verilog: dict[str, str] = {}
        for v_path in rust_dest.glob("*.v"):
            rust_verilog[v_path.stem] = v_path.read_text(encoding="utf-8")

    # Compare the intersection of modules both pipelines produce. FSM
    # modules are included now that Rust attaches the real Vitis-generated
    # FSM RTL via `build_project_from_paths` instead of synthesizing a
    # stub.
    common = set(py_verilog) & set(rust_verilog)
    # At minimum these must be present and comparable on both sides.
    required = {
        "fifo",
        "reset_inverter",
        "VecAdd_control_s_axi",
        "VecAdd_fsm",
        "SLOT_X0Y2_SLOT_X0Y2_fsm",
        "SLOT_X2Y3_SLOT_X2Y3_fsm",
        "SLOT_X3Y3_SLOT_X3Y3_fsm",
    }
    assert required.issubset(common), (
        f"infrastructure modules missing from one side:\n"
        f"  python: {sorted(set(py_verilog))}\n"
        f"  rust:   {sorted(set(rust_verilog))}\n"
        f"  common: {sorted(common)}"
    )

    mismatches: list[str] = []
    for module in sorted(common):
        try:
            py_parsed = rtl.parse(py_verilog[module])
        except Exception as exc:  # noqa: BLE001
            mismatches.append(f"{module}: python export unparsable: {exc}")
            continue
        try:
            rust_parsed = rtl.parse(rust_verilog[module])
        except Exception as exc:  # noqa: BLE001
            mismatches.append(f"{module}: rust export unparsable: {exc}")
            continue
        py_ports = {p["name"] for p in py_parsed.get("ports") or []}
        rust_ports = {p["name"] for p in rust_parsed.get("ports") or []}
        if py_ports != rust_ports:
            mismatches.append(
                f"{module}: port-name mismatch\n"
                f"  python-only: {sorted(py_ports - rust_ports)}\n"
                f"  rust-only:   {sorted(rust_ports - py_ports)}"
            )

    assert not mismatches, "parsed Verilog differs on:\n" + "\n".join(mismatches)


def _try_export(graphir_export: Any, project: dict[str, Any], dest: Path) -> str | None:
    """Run `export_project` and return any error message string, or None on success."""
    try:
        graphir_export.export_project(json.dumps(project), str(dest))
    except ValueError as exc:
        return str(exc)
    return None


def _build_drc_clean_grouped_project() -> dict[str, Any]:
    """Construct a minimal DRC-clean grouped Project dict.

    Shape: one `fifo` module (infrastructure), one grouped top module
    ``minimal_top`` that instantiates a single `fifo_0`. Every signal
    referenced in any connection expression is declared as either a top
    port or a top wire, so `check_missing_wire` passes cleanly on both
    Python and Rust exporters — unlike the shared VecAdd fixture.
    """

    def _tok_id(s: str) -> dict[str, Any]:
        return {"type": "id", "repr": s}

    def _tok_lit(s: str) -> dict[str, Any]:
        return {"type": "lit", "repr": s}

    def _port(name: str, pt: str, rng: Any = None) -> dict[str, Any]:
        return {
            "name": name,
            "hierarchical_name": [name],
            "type": pt,
            "range": rng,
        }

    def _wire(name: str, rng: Any = None) -> dict[str, Any]:
        return {"name": name, "hierarchical_name": [name], "range": rng}

    def _conn(name: str, expr: list[dict[str, Any]]) -> dict[str, Any]:
        return {"name": name, "hierarchical_name": [name], "expr": expr}

    def _param(name: str, expr: list[dict[str, Any]]) -> dict[str, Any]:
        return {"name": name, "hierarchical_name": [name], "expr": expr}

    data_range = {
        "left": [_tok_id("DATA_WIDTH"), _tok_lit("-"), _tok_lit("1")],
        "right": [_tok_lit("0")],
    }
    fifo_def = {
        "module_type": "verilog_module",
        "name": "fifo",
        "hierarchical_name": None,
        "parameters": [
            _param("DATA_WIDTH", [_tok_lit("32")]),
            _param("ADDR_WIDTH", [_tok_lit("5")]),
            _param("DEPTH", [_tok_lit("32")]),
        ],
        "ports": [
            _port("clk", "input wire"),
            {
                "name": "reset",
                "hierarchical_name": ["rst"],
                "type": "input wire",
                "range": None,
            },
            _port("if_full_n", "output wire"),
            _port("if_write_ce", "input wire"),
            _port("if_write", "input wire"),
            _port("if_din", "input wire", data_range),
            _port("if_empty_n", "output wire"),
            _port("if_read_ce", "input wire"),
            _port("if_read", "input wire"),
            _port("if_dout", "output wire", data_range),
        ],
        "verilog": "module fifo; endmodule\n",
        "submodules_module_names": [],
    }
    fifo_inst = {
        "name": "fifo_0",
        "hierarchical_name": ["fifo_0"],
        "module": "fifo",
        "connections": [
            _conn("clk", [_tok_id("ap_clk")]),
            _conn("reset", [_tok_id("rst")]),
            _conn("if_din", [_tok_id("d_din")]),
            _conn("if_full_n", [_tok_id("d_full_n")]),
            _conn("if_write", [_tok_id("d_write")]),
            _conn("if_dout", [_tok_id("d_dout")]),
            _conn("if_empty_n", [_tok_id("d_empty_n")]),
            _conn("if_read", [_tok_id("d_read")]),
            _conn("if_read_ce", [_tok_lit("1'b1")]),
            _conn("if_write_ce", [_tok_lit("1'b1")]),
        ],
        "parameters": [
            _param("DATA_WIDTH", [_tok_lit("32")]),
            _param("ADDR_WIDTH", [_tok_lit("5")]),
            _param("DEPTH", [_tok_lit("32")]),
        ],
        "floorplan_region": None,
        "area": None,
    }
    top_def = {
        "module_type": "grouped_module",
        "name": "minimal_top",
        "hierarchical_name": None,
        "parameters": [],
        "ports": [
            _port("ap_clk", "input wire"),
            _port("rst", "input wire"),
        ],
        "wires": [
            _wire("d_din"),
            _wire("d_dout"),
            _wire("d_full_n"),
            _wire("d_empty_n"),
            _wire("d_read"),
            _wire("d_write"),
        ],
        "submodules": [fifo_inst],
    }
    return {
        "part_num": None,
        "modules": {
            "name": "$root",
            "module_definitions": [fifo_def, top_def],
            "top_name": "minimal_top",
        },
        "blackboxes": [],
        "ifaces": None,
        "module_to_rtl_pragmas": None,
        "module_to_old_rtl_pragmas": None,
        "island_to_pblock_range": None,
        "routes": None,
        "resource_to_max_local_usage": None,
        "cut_to_crossing_count": None,
    }


def test_parity_drc_clean_grouped_fixture_crosslang() -> None:  # noqa: PLR0914
    """Python-vs-Rust grouped-module export parity on a DRC-clean fixture.

    Constructs a minimal DRC-clean grouped Project whose top module's
    connections reference only declared wires / ports. Exports the
    project via both Python (`tapa.verilog.graphir_exporter.export_design`)
    and Rust (`tapa_core.graphir_export.export_project`) without any DRC
    failures, then re-parses both grouped `.v` outputs via `tapa-rtl` and
    asserts full normalized structural equality of the parsed grouped
    modules: module name, parameters, ports, signals, pragmas, and
    submodule instantiations (module name + instance name pairs). The
    raw source text is excluded from equality (formatting / whitespace
    differs between emitters), but every semantic element the RTL
    parser exposes must match.
    """
    _require_fixture()
    from tapa_core import graphir_export, rtl  # type: ignore[import-not-found]

    from tapa.graphir.types import (
        Project as PyProject,  # type: ignore[import-not-found]
    )
    from tapa.verilog.graphir_exporter.main import (
        export_design,  # type: ignore[import-not-found]
    )

    project_dict = _build_drc_clean_grouped_project()
    project_json = json.dumps(project_dict)

    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        py_dest = tmp_path / "py"
        py_dest.mkdir()
        rust_dest = tmp_path / "rust"
        rust_dest.mkdir()

        # Python export
        py_project = PyProject.model_validate_json(project_json)
        export_design(py_project, str(py_dest))

        # Rust export
        graphir_export.export_project(project_json, str(rust_dest))

        py_grouped = (py_dest / "minimal_top.v").read_text(encoding="utf-8")
        rust_grouped = (rust_dest / "minimal_top.v").read_text(encoding="utf-8")

        py_parsed = rtl.parse(py_grouped)
        rust_parsed = rtl.parse(rust_grouped)
        py_insts = rtl.extract_instance_names(py_grouped)
        rust_insts = rtl.extract_instance_names(rust_grouped)

    def _normalize(parsed: dict[str, Any]) -> dict[str, Any]:
        # Drop `source` (formatting differs); sort lists that have no
        # semantic order. Ports preserve declaration order which is part
        # of the module interface signature.
        return {
            "name": parsed["name"],
            "parameters": sorted(
                parsed.get("parameters") or [],
                key=lambda p: p.get("name", ""),
            ),
            "ports": list(parsed.get("ports") or []),
            "signals": sorted(
                parsed.get("signals") or [],
                key=lambda s: s.get("name", ""),
            ),
            "pragmas": list(parsed.get("pragmas") or []),
        }

    py_norm = _normalize(py_parsed)
    rust_norm = _normalize(rust_parsed)
    assert py_norm == rust_norm, (
        f"grouped-module structural mismatch:\n  py:   {py_norm}\n  rust: {rust_norm}"
    )

    # Submodule instantiations compared as sets of (module, instance)
    # pairs — instance order is not semantically meaningful here.
    py_inst_set = {tuple(p) for p in py_insts}
    rust_inst_set = {tuple(p) for p in rust_insts}
    assert py_inst_set == rust_inst_set, (
        f"grouped-module submodule instantiations differ:\n"
        f"  py:   {sorted(py_inst_set)}\n  rust: {sorted(rust_inst_set)}"
    )
    assert len(py_insts) == len(rust_insts), (
        f"instance count differs: py={len(py_insts)} rust={len(rust_insts)}"
    )


def test_parity_grouped_module_rust_reparses() -> None:
    """Grouped-module structural parity via Rust exporter roundtrip.

    Python's exporter raises DRC missing-wire errors on every grouped module
    in the VecAdd fixture (``SLOT_X0Y2_*``, ``SLOT_X2Y3_*``, ``SLOT_X3Y3_*``,
    ``VecAdd``). Once Rust's wire synthesis matches Python's
    ``get_upper_task_ir_wires`` exactly , the Rust exporter
    raises the same DRC on the same fixture. That's consistent parity
    with Python, not a regression. ``test_parity_drc_clean_grouped_fixture_crosslang``
    covers cross-language parity on a DRC-clean fixture; this test keeps
    per-module structural validation of Rust's exporter when the shared
    VecAdd fixture's grouped modules happen to export cleanly.
    """
    _require_fixture()
    from tapa_core import graphir_export, rtl  # type: ignore[import-not-found]

    with tempfile.TemporaryDirectory() as rust_tmp:
        rust_project = _build_rust_project(Path(rust_tmp))
        rust_dest = Path(rust_tmp) / "rust_export"
        rust_dest.mkdir()
        exc = _try_export(graphir_export, rust_project, rust_dest)
        if exc is not None:
            # Expected on the shared fixture; Python exporter fails the
            # same way on the same inputs.
            assert "DRC failure" in exc or "missing" in exc.lower(), (
                f"unexpected export error: {exc}"
            )
            return

        grouped_names = [
            m["name"]
            for m in rust_project["modules"]["module_definitions"]
            if m.get("module_type") == "grouped_module"
        ]
        assert grouped_names, "expected grouped modules on the Rust side"

        for gname in grouped_names:
            v_path = rust_dest / f"{gname}.v"
            assert v_path.exists(), f"rust exporter missed {gname}.v"
            v = v_path.read_text(encoding="utf-8")
            # Grouped exports must be re-parseable by tapa-rtl.
            parsed = rtl.parse(v)
            assert parsed["name"] == gname, (
                f"grouped {gname}.v re-parsed as {parsed.get('name')!r}"
            )
            # Structural invariants: non-empty port list, matching
            # module / endmodule declarations.
            assert parsed.get("ports"), f"{gname} has no ports after reparse"
            # Structural balance: has at least one `module` and `endmodule`
            # declaration, and the two counts match.
            module_count = v.count("\nmodule ") + (1 if v.startswith("module ") else 0)
            endmodule_count = v.count("endmodule")
            assert module_count > 0 and module_count == endmodule_count, (
                f"{gname}.v is not module/endmodule balanced "
                f"(module={module_count}, endmodule={endmodule_count})"
            )


def test_parity_rust_exported_fifo_reparses() -> None:
    """Verilog emitted by the Rust exporter re-parses with tapa-rtl.

    The shared VecAdd fixture has DRC-missing wires on every grouped
    module once the Rust wire synthesis matches Python's
    `get_upper_task_ir_wires` exactly Python's own
    grouped export fails on the same fixture — it's a fixture-side gap.
    We test the `fifo.v` module (non-grouped) by exporting only that
    single module so DRC doesn't block the test.
    """
    _require_fixture()
    from tapa_core import graphir_export, rtl  # type: ignore[import-not-found]

    with tempfile.TemporaryDirectory() as rust_tmp:
        rust_project = _build_rust_project(Path(rust_tmp))
        # Export only the `fifo` module so grouped-module DRC failures on
        # this shared fixture do not block the test. Both Python and Rust
        # fail grouped-module DRC on `top_conversion_test_files` — that's
        # a fixture issue, not a pipeline-parity issue.
        fifo_only = {
            **rust_project,
            "modules": {
                **rust_project["modules"],
                "module_definitions": [
                    m
                    for m in rust_project["modules"]["module_definitions"]
                    if m["name"] == "fifo"
                ],
                "top_name": "fifo",
            },
            "ifaces": None,
        }
        rust_dest = Path(rust_tmp) / "rust_export"
        rust_dest.mkdir()
        graphir_export.export_project(json.dumps(fifo_only), str(rust_dest))
        rust_fifo = (rust_dest / "fifo.v").read_text(encoding="utf-8")

    rust_fifo_parsed = rtl.parse(rust_fifo)
    assert rust_fifo_parsed["name"] == "fifo"
    rust_ports = {p["name"] for p in rust_fifo_parsed["ports"]}
    expected_ports = {
        "clk",
        "reset",
        "if_din",
        "if_dout",
        "if_empty_n",
        "if_full_n",
        "if_read",
        "if_read_ce",
        "if_write",
        "if_write_ce",
    }
    assert expected_ports.issubset(rust_ports), (
        f"fifo.v missing expected ports: {expected_ports - rust_ports}"
    )


# ─────────────────────────────────────────────────────────────────────
# Phase 6: tapa_core.xilinx parity (report parser + device info + CFLAGS)
# ─────────────────────────────────────────────────────────────────────

_XILINX_TESTDATA = _REPO_ROOT / "tapa-core" / "tapa-xilinx" / "testdata" / "xilinx"


@pytest.fixture(scope="module")
def xilinx_mod() -> Any:
    try:
        return importlib.import_module("tapa_core.xilinx")
    except ImportError as exc:  # pragma: no cover - allowed when bindings absent
        pytest.skip(f"tapa_core.xilinx not importable: {exc}")


def test_parity_xilinx_device_info(xilinx_mod: Any) -> None:
    """Rust vs Python parse_device_info on a staged platform directory.

    Both sides consume the same layout.
    """
    from tapa.backend import device_config as py_device_config

    xpfm = _XILINX_TESTDATA / "sample.xpfm"
    if not xpfm.is_file():
        pytest.skip(f"missing fixture {xpfm}")

    import shutil
    import tempfile

    with tempfile.TemporaryDirectory() as td:
        platform_dir = Path(td) / "shell"
        (platform_dir / "hw").mkdir(parents=True)
        shutil.copy(xpfm, platform_dir / "hw" / "shell.xsa")
        py_info = py_device_config.get_device_info(str(platform_dir))
        rust_info_json = xilinx_mod.parse_device_info(str(platform_dir))
    rust_info = json.loads(rust_info_json)
    assert py_info["part_num"] == rust_info["part_num"]
    assert str(py_info["clock_period"]) == rust_info["clock_period"]


def test_parity_xilinx_cflags_full_vector_from_tempdir(xilinx_mod: Any) -> None:
    """AC-2 regression: full CFLAGS parity from an out-of-repo cwd.

    Rust must resolve TAPA runtime include directories via the
    bindings anchor (set by xilinx::register from the loaded
    tapa_core extension's __file__) even when the process cwd is
    outside the repo checkout root.
    """
    import tempfile

    from tapa.common.paths import get_tapa_cflags as py_get_tapa_cflags

    prior = os.getcwd()
    try:
        with tempfile.TemporaryDirectory() as td:
            os.chdir(td)
            rust_flags = list(xilinx_mod.get_cflags("tapa"))
            py_flags = list(py_get_tapa_cflags())
    finally:
        os.chdir(prior)
    assert rust_flags == py_flags, (
        f"full cflags diverged from tempdir cwd:\n  py   = {py_flags}\n"
        f"  rust = {rust_flags}"
    )


def test_parity_xilinx_cflags_tail(xilinx_mod: Any) -> None:
    """Rust and Python CFLAGS tails match (suppression + builtin-define block).

    Compares the trailing slice of Rust's `get_cflags("tapa")` against
    Python's `get_tapa_cflags()` tail. The leading `-isystem` entries
    come from `find_resource()` discovery and vary across host layouts,
    so only the deterministic tail is asserted.
    """
    from tapa.common.paths import get_tapa_cflags as py_get_tapa_cflags

    py_flags = list(py_get_tapa_cflags())
    rust_flags = list(xilinx_mod.get_cflags("tapa"))

    py_suppressions = [f for f in py_flags if not f.startswith("-isystem")]
    rust_suppressions = [f for f in rust_flags if not f.startswith("-isystem")]
    assert py_suppressions == rust_suppressions, (
        f"non-include flags diverged:\n  py   = {py_suppressions}\n"
        f"  rust = {rust_suppressions}"
    )


def _py_parse_csynth(fixture: Path) -> dict[str, str]:
    """Reference csynth.xml parser using Python's xml.etree.

    Mirrors the handful of fields `tapa_xilinx::parse_csynth_xml` emits
    so we can assert cross-language equality against the same source.
    """
    from xml.etree import ElementTree as ET

    tree = ET.parse(fixture)
    root = tree.getroot()
    out: dict[str, str] = {}
    mapping = {
        "top": ("TopModelName", "TopModuleName"),
        "part": ("Part",),
        "target_clock_period_ns": ("TargetClockPeriod", "CTargetClockPeriod"),
        "estimated_clock_period_ns": ("EstimatedClockPeriod",),
    }
    for key, candidates in mapping.items():
        for tag in candidates:
            match = root.find(f".//{tag}")
            if match is not None and match.text:
                out[key] = match.text.strip()
                break
    return out


def test_parity_xilinx_csynth_report(xilinx_mod: Any) -> None:
    """Rust vs Python csynth.xml parse on the same fixture.

    Field-for-field comparison against a Python xml.etree reference.
    """
    fixture = _XILINX_TESTDATA / "sample.csynth.xml"
    if not fixture.is_file():
        pytest.skip(f"missing fixture {fixture}")
    rust_payload = json.loads(xilinx_mod.parse_csynth_xml(fixture.read_bytes()))
    py_payload = _py_parse_csynth(fixture)
    for key, value in py_payload.items():
        assert rust_payload.get(key) == value, (
            f"csynth field {key}: py={value!r} rust={rust_payload.get(key)!r}"
        )


def _py_parse_utilization(text: str) -> dict[str, Any]:
    """Reference utilization.rpt walker in Python.

    Simplified port of `tapa/backend/report/xilinx/rtl/parser.py`: one
    root instance, hierarchical children by leading-indent depth.
    """
    device = ""
    schema: list[str] = []
    state = "prolog"
    root: dict[str, Any] | None = None
    stack: list[tuple[int, dict[str, Any]]] = []
    for line in text.splitlines():
        stripped = line.strip()
        words = stripped.split()
        if len(words) == 4 and words[:3] == ["|", "Device", ":"]:  # noqa: PLR2004
            device = words[3]
            continue
        if stripped and all(c in "+-" for c in stripped):
            state = {"prolog": "header", "header": "body", "body": "done"}.get(
                state, state
            )
            if state == "done":
                break
            continue
        if not stripped:
            continue
        inner = stripped.strip("|")
        parts = inner.split("|")
        inst_raw = parts[0]
        cols = [c.strip() for c in parts[1:]]
        if state == "header":
            schema = [c.strip() for c in cols]
            continue
        if state == "body":
            depth = (len(inst_raw) - len(inst_raw.lstrip(" "))) // 2
            instance = inst_raw.strip()
            node: dict[str, Any] = {
                "device": device,
                "instance": instance,
                "metrics": dict(zip(schema, cols, strict=False)),
                "children": [],
            }
            while stack and stack[-1][0] >= depth:
                stack.pop()
            if stack:
                stack[-1][1]["children"].append(node)
            else:
                root = node
            stack.append((depth, node))
    assert root is not None
    return root


def test_parity_xilinx_utilization(xilinx_mod: Any) -> None:
    """Rust vs Python utilization.rpt walker on the same fixture.

    Hierarchical, metric-exact equality.
    """
    fixture = _XILINX_TESTDATA / "sample.utilization.rpt"
    if not fixture.is_file():
        pytest.skip(f"missing fixture {fixture}")
    text = fixture.read_text(encoding="utf-8")
    rust_payload = json.loads(xilinx_mod.parse_utilization_rpt(text))
    py_payload = _py_parse_utilization(text)
    assert rust_payload["device"] == py_payload["device"]
    assert rust_payload["instance"] == py_payload["instance"]
    assert rust_payload["metrics"] == py_payload["metrics"]
    assert len(rust_payload["children"]) == len(py_payload["children"])
    for r_child, p_child in zip(
        rust_payload["children"], py_payload["children"], strict=False
    ):
        assert r_child["instance"] == p_child["instance"]
        assert r_child["metrics"] == p_child["metrics"]


def test_parity_xilinx_kernel_xml_direct(xilinx_mod: Any) -> None:
    """Direct Rust-vs-Python kernel.xml parity on the same arg list.

    Emits the MMAP + scalar argument set via both
    `tapa.backend.kernel_metadata.print_kernel_xml` and the Rust
    `tapa_core.xilinx.emit_kernel_xml`, then compares the
    whitespace-canonical token streams. Does not depend on the
    committed golden file.
    """
    try:
        from tapa.backend.kernel_metadata import Arg, Cat, print_kernel_xml
    except ImportError as exc:  # pragma: no cover
        pytest.skip(f"python kernel_metadata not importable: {exc}")

    import io

    args = [
        Arg(cat=Cat.MMAP, name="a", port="", ctype="int*", width=512),
        Arg(cat=Cat.SCALAR, name="n", port="", ctype="int", width=32),
    ]
    buf = io.StringIO()
    print_kernel_xml("vadd", args, buf)
    py_xml = buf.getvalue()

    rust_payload = {
        "top_name": "vadd",
        "clock_period": "3.33",
        "ports": [
            {
                "name": "a",
                "category": "MAxi",
                "width": 512,
                "port": "",
                "ctype": "int*",
            },
            {
                "name": "n",
                "category": "Scalar",
                "width": 32,
                "port": "",
                "ctype": "int",
            },
        ],
    }
    rust_xml = xilinx_mod.emit_kernel_xml(json.dumps(rust_payload))

    py_tokens = " ".join(py_xml.split())
    rust_tokens = " ".join(rust_xml.split())
    assert py_tokens == rust_tokens, (
        f"kernel.xml parity failed:\n  py   = {py_tokens}\n  rust = {rust_tokens}"
    )


def test_parity_xilinx_kernel_xml_round_trip() -> None:
    """Python print_kernel_xml output matches the committed golden.

    Ensures the golden file Rust emits against stays in sync with the
    Python template.
    """
    golden = _XILINX_TESTDATA / "kernel_xml.golden.xml"
    if not golden.is_file():
        pytest.skip(f"missing golden {golden}")
    try:
        from tapa.backend.kernel_metadata import Arg, Cat, print_kernel_xml
    except ImportError as exc:  # pragma: no cover - import surface varies
        pytest.skip(f"python kernel_metadata not importable: {exc}")

    import io

    args = [
        Arg(cat=Cat.MMAP, name="a", port="", ctype="int*", width=512),
        Arg(cat=Cat.SCALAR, name="n", port="", ctype="int", width=32),
    ]
    buf = io.StringIO()
    print_kernel_xml("vadd", args, buf)
    py_xml = buf.getvalue().strip()
    # Strip whitespace differences for canonical comparison.
    golden_text = golden.read_text(encoding="utf-8").strip()
    py_tokens = " ".join(py_xml.split())
    golden_tokens = " ".join(golden_text.split())
    assert py_tokens == golden_tokens, (
        "Python kernel.xml drifted from committed golden — regenerate or "
        "update the fixture before changing emit_kernel_xml."
    )
