"""Development and test tools."""

load("//bazel:cargo_rules.bzl", "cargo_artifacts")

package(default_visibility = ["//visibility:public"])

cargo_artifacts(
    name = "test_tools",
    srcs = [
        "test-tools/Cargo.lock",
        "test-tools/Cargo.toml",
        "test-tools/src/main.rs",
    ],
    outs = ["bin/tapa-test-tools"],
    artifacts = ["tapa-test-tools:bin/tapa-test-tools"],
    build_args = [],
    executable = True,
    executable_outputs = ["bin/tapa-test-tools"],
    manifest = "test-tools/Cargo.toml",
    tags = ["requires-network"],
)
