"""Preprocess the config file for the cosimulation."""

import glob
import json
import logging
import os
import shutil
import sys
import zipfile
from pathlib import Path
from typing import TypeVar, cast
from xml.etree import ElementTree as ET

from pydantic import BaseModel, ConfigDict, Field
from yaml import safe_load

from tapa.cosim.common import Arg, Port

_logger = logging.getLogger().getChild(__name__)

_V = TypeVar("_V")


def _remap_keys(id_to_name: dict[int, str], id_to_val: dict[str, _V]) -> dict[str, _V]:
    """Remap dict keys from integer argument IDs to qualified argument names."""
    return {id_to_name[int(arg_id)]: val for arg_id, val in id_to_val.items()}


class CosimConfig(BaseModel):
    """Typed schema for cosim configuration.

    Input fields come from the JSON config file; computed fields are populated
    by the preprocessing pipeline before the config is used by callers.
    """

    model_config = ConfigDict(arbitrary_types_allowed=True, frozen=False)

    # --- Input fields (from the JSON config file) ---
    xo_path: str
    axi_to_data_file: dict[str, str] = Field(default_factory=dict)
    scalar_to_val: dict[str, str] = Field(default_factory=dict)
    # Values are array sizes (integers), keys are argument IDs (later mapped to names)
    axi_to_c_array_size: dict[str, int] = Field(default_factory=dict)
    axis_to_data_file: dict[str, str] = Field(default_factory=dict)

    # --- Computed fields (populated during preprocessing) ---
    mode: str = ""
    verilog_path: str = ""
    top_name: str = ""
    top_is_leaf_task: bool = False
    args: list[Arg] = Field(default_factory=list)
    part_num: str | None = None

    # Backward-compatibility: allow callers to do config["key"] / config["key"] = v
    def __getitem__(self, key: str) -> object:
        return getattr(self, key)

    def __setitem__(self, key: str, value: object) -> None:
        setattr(self, key, value)

    def __contains__(self, key: str) -> bool:
        return key in self.model_fields

    def get(self, key: str, default: object = None) -> object:
        """Return the field value, or default if the field does not exist."""
        try:
            return getattr(self, key)
        except AttributeError:
            return default


def _update_relative_path(config: CosimConfig, config_path: str) -> None:
    """Convert the relative path in the config file."""
    config_dir = os.path.dirname(config_path)

    def _resolve(path: str) -> str:
        if not path.startswith("/") and not path.startswith("~"):
            return os.path.join(config_dir, path)
        return path

    config.xo_path = _resolve(config.xo_path)
    config.axi_to_data_file = {
        k: _resolve(v) for k, v in config.axi_to_data_file.items()
    }


def extract_part_from_xml_file(file_path: str) -> str | None:
    """Extracts the <Part> element from the given XML file.

    Args:
        file_path (str): The path to the XML file.
    """
    try:
        tree = ET.parse(file_path)
    except (ET.ParseError, FileNotFoundError) as e:
        return f"Error reading or parsing the XML file: {e}"

    root = tree.getroot()
    part_element = root.find(".//Part")

    if part_element is None:
        msg = "The XML file does not contain a <Part> element."
        raise ValueError(msg)

    return part_element.text


def parse_part_num(xo_dir: str) -> str | None:
    """Extract the part number from the xo directory."""
    report_dir = f"{xo_dir}/report"
    if not os.path.exists(report_dir):
        _logger.warning(
            "The report directory %s does not exist inside xo, check if the "
            "xo is generated by the latest TAPA",
            report_dir,
        )
        return None

    csynth_reports = glob.glob(f"{report_dir}/*_csynth.xml")
    if not csynth_reports:
        _logger.warning(
            "No csynth report found in %s, check if the xo is generated by "
            "the latest TAPA",
            report_dir,
        )
        return None

    return extract_part_from_xml_file(csynth_reports[0])


def _parse_and_update_config(config: CosimConfig, tb_output_dir: str) -> None:
    """Only supports TAPA xo.

    Vitis XO has different hierarchy and RTL coding style.
    """
    xo_path = config.xo_path

    tmp_path = f"{tb_output_dir}/tapa_fast_cosim_{os.getuid()}/"
    shutil.rmtree(tmp_path, ignore_errors=True)
    Path(tmp_path).mkdir(parents=True, exist_ok=True)
    shutil.copy(xo_path, f"{tmp_path}/target.xo")
    zip_ref = zipfile.ZipFile(f"{tmp_path}/target.xo", "r")
    zip_ref.extractall(tmp_path)

    if xo_path.endswith(".xo"):
        config.mode = "vitis"
        _parse_xo_update_config(config, tmp_path)
    elif xo_path.endswith(".zip"):
        config.mode = "hls"
        _parse_zip_update_config(config, tmp_path)
    else:
        msg = f"Unsupported xo file format: {xo_path}"
        raise ValueError(msg)

    # convert argument index in the config file to actual names
    id_to_name = {arg.id: arg.qualified_name for arg in config.args}
    config.scalar_to_val = _remap_keys(id_to_name, config.scalar_to_val)
    config.axi_to_data_file = _remap_keys(id_to_name, config.axi_to_data_file)
    config.axis_to_data_file = _remap_keys(id_to_name, config.axis_to_data_file)
    config.axi_to_c_array_size = _remap_keys(id_to_name, config.axi_to_c_array_size)


def _parse_xo_update_config(config: CosimConfig, tmp_path: str) -> None:
    """Parse the xo file and update the config file with the extracted information.

    Args:
        config (CosimConfig): The configuration object.
        tmp_path (str): The temporary directory path.
    """
    # only supports tapa xo
    src_dirs = glob.glob(f"{tmp_path}/ip_repo/*/src")
    assert len(src_dirs) == 1, "Only supports TAPA XO. Vitis XO is not supported"
    config.verilog_path = src_dirs[0]

    # extract other kernel information
    kernel_file_path = glob.glob(f"{tmp_path}/*/kernel.xml")[0]
    kernel_xml = ET.parse(kernel_file_path).getroot().find("./kernel")
    if kernel_xml is None:
        _logger.error("Fail to extract kernel name")
        sys.exit(1)
    config.top_name = kernel_xml.attrib["name"]
    # Vitis mode does not support a leaf task as top task
    config.top_is_leaf_task = False

    # parse kernel ports and args
    ports = {}
    for port_xml in kernel_xml.findall("./ports/port"):
        port = Port(
            name=port_xml.attrib["name"],
            mode=port_xml.attrib["mode"],
            data_width=int(port_xml.attrib["dataWidth"]),
        )
        ports[port.name] = port
        _logger.debug("port: %s", port)
    args = []
    for arg_xml in kernel_xml.findall("./args/arg"):
        arg = Arg(
            name=arg_xml.attrib["name"],
            address_qualifier=int(arg_xml.attrib["addressQualifier"]),
            id=int(arg_xml.attrib["id"]),
            port=ports[arg_xml.attrib["port"]],
        )
        args.append(arg)
        _logger.debug("arg: %s", arg)
    config.args = args

    config.part_num = parse_part_num(tmp_path)


def _parse_zip_ports(ports_yaml: list[dict[str, object]]) -> list[Arg]:
    """Parse port descriptors from graph.yaml into a list of Arg objects."""
    args: list[Arg] = []
    idx = 0
    for port in ports_yaml:
        cat = port["cat"]
        if cat in {"istream", "istreams"}:
            address_qualifier = 4
            mode = "read_only"
        elif cat in {"ostream", "ostreams"}:
            address_qualifier = 4
            mode = "write_only"
        elif cat in {"mmap", "async_mmap"}:
            address_qualifier = 1
            mode = "read_write"
        elif cat in {"mmaps", "hmap"}:
            # Array mmap types: expand into individual mmap entries.
            chan_count = cast("int", port["chan_count"])
            for i in range(chan_count):
                port_name = f"{cast('str', port['name'])}_{i}"
                args.append(
                    Arg(
                        name=port_name,
                        address_qualifier=1,
                        id=idx,
                        stream_idx=None,
                        port=Port(
                            name=port_name,
                            mode="read_write",
                            data_width=cast("int", port["width"]),
                        ),
                    )
                )
                idx += 1
            continue
        elif cat == "scalar":
            address_qualifier = 0
            mode = "read_only"
        else:
            msg = f"Unsupported port category: {cat}"
            raise ValueError(msg)

        # Multi-channel stream types expand into one entry per channel.
        stream_indices: range | list = (
            range(cast("int", port["chan_count"]))
            if cat in {"istreams", "ostreams"}
            else [None]
        )
        for stream_idx in stream_indices:
            port_name = cast("str", port["name"])
            args.append(
                Arg(
                    name=port_name,
                    address_qualifier=address_qualifier,
                    id=idx,
                    stream_idx=stream_idx,
                    port=Port(
                        name=port_name,
                        mode=mode,
                        data_width=cast("int", port["width"]),
                    ),
                )
            )
            idx += 1

    return args


def _parse_zip_update_config(config: CosimConfig, tmp_path: str) -> None:
    """Parse the zip file and update the config file with the extracted information.

    Args:
        config (CosimConfig): The configuration object.
        tmp_path (str): The temporary directory path.
    """
    rtl_dir = Path(tmp_path) / "rtl"
    # only supports tapa generated zip file
    assert rtl_dir.is_dir(), "Only supports TAPA XO. Vitis XO is not supported"
    config.verilog_path = str(rtl_dir)

    # extract other kernel information
    graph_file_path = Path(tmp_path) / "graph.yaml"
    assert graph_file_path.is_file(), "Fail to extract kernel information"
    with graph_file_path.open(encoding="utf-8") as f:
        graph = safe_load(f)
        config.top_name = graph["top"]
        config.top_is_leaf_task = graph["tasks"][config.top_name]["level"] == "lower"
        config.args = _parse_zip_ports(graph["tasks"][config.top_name]["ports"])

    settings_file_path = Path(tmp_path) / "settings.yaml"
    assert settings_file_path.is_file(), "Fail to extract kernel settings"
    with settings_file_path.open(encoding="utf-8") as f:
        settings = safe_load(f)
        config.part_num = settings["part_num"]


def _check_scalar_val_format(config: CosimConfig) -> None:
    for scalar, val in config.scalar_to_val.items():
        assert val.startswith("'h"), (
            "scalar value should be written in hex format, lsb on the right, "
            "with the suffix 'h according to Verilog syntax. "
            f"Violation: {scalar}: {val}"
        )
        assert len(val) <= 2 + 16, (
            f"scalar value should be at most 64 bit. Violation: {scalar}: {val}"
        )


def preprocess_config(
    config_path: str, tb_output_dir: str, part_num: str | None
) -> CosimConfig:
    """Preprocess the config file."""
    with open(config_path, encoding="utf-8") as fp:
        config = CosimConfig.model_validate(json.load(fp))

    _update_relative_path(config, config_path)
    _parse_and_update_config(config, tb_output_dir)
    _check_scalar_val_format(config)

    # overwrite part number if provided
    if part_num:
        config.part_num = part_num

    return config
